### Setup libraries
Download necessary libraries
```{r setup, include = FALSE}
path <- "C:/Users/claraba/Documents/PhD_work/Papers/SteelREMIND/Analysis/RIKEN"
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(
    root.dir = path
    )

require(ggplot2)
require(tidyverse)
require(mrremind)
require(magclass)
library(quitte)
require(quitte)
library(dplyr)
library(gridExtra)
library(grid)
```

```{r load data}
setwd("C:/Users/claraba/Documents/PhD_work/Papers/SteelREMIND/AnalysisScript")
mifdata <- read.quitte("REMIND_generic_default.mif")


```

```{r change data, echo = FALSE}

steel_df <- mifdata %>%
  filter(str_detect(variable, "Steel")) %>%
  filter(str_detect(variable, "Production"))

#filter breakdown of steel production
prsteel_df <- mifdata %>%
  filter(grepl("Production|Industry|Steel|+",
                variable,
                ignore.case = TRUE, 
                fixed = TRUE)) %>% # nolint
  filter(#period == 2020,
         region == "World",
         unit == "Mt/yr",
         #scenario == "SSP2-Base",
         )

#playing around, exploring steel parameters
steel_df <- mifdata %>%
  filter(grepl("Production|Industry|Steel",
                variable,
                ignore.case = TRUE, 
                fixed = TRUE)) %>% # nolint
  filter(period == 2020,
         region == "World",
         unit != "Mt/yr",
         #scenario == "SSP2-Base",
         )
steel_df$variable
```

```{r plot, echo = FALSE}	

# filter out secondary steel for now
prsteel_df <- prsteel_df %>% 
  filter(variable != "Production|Industry|Steel|+|SCRAP-EAF")

# Reorder levels of 'variable' factor
prsteel_df$variable <- factor(prsteel_df$variable,
                               levels = c(rev(levels(prsteel_df$variable))),# nolint
                               #labels = c(rev(levels(prsteel_df$variable)[!levels(prsteel_df$variable) %in% secondary_steel],)secondary_steel),# nolint
                               )

# Steel production Plot:
# TODO: separate primary and secondary steel somehow
ggplot(prsteel_df, aes(x = period)) +
  geom_area(aes(y = value, fill = variable), alpha = 0.5) +
  labs(title = "Primary Steel production by technology type",
       x = "Time",
       y = "Primary Steel Production (Mt/yr)") +
  theme_minimal()

#Plot steel CO2 emissions intensity + share of secondary steel in total mix on the same graph (different y axes?)

```

```{r RIKEN load, echo = FALSE}
setwd("C:/Users/claraba/Documents/PhD_work/Papers/SteelREMIND/AnalysisScript/RIKEN")
#riken mifs
early_trans <- read.quitte("REMIND_generic_EarlyTransitionPathway_LowLockIn.mif")
prolonged_lockin <- read.quitte("REMIND_generic_ProlongedFossilSteelLockIn.mif")
extended_lockin <- read.quitte("REMIND_generic_ExtendedFossilDependence.mif")
statusquo <- read.quitte("REMIND_generic_StatusQuoLockIn.mif")

```

```{r RIKEN filter, echo = FALSE}

filter_mifdata <- function(df) {
  df %>%
    filter(grepl("Emi|CO2|Energy|Demand|Industry|Steel|+",
                # "Emi|CO2|Energy|Demand|Industry|Steel", # if we want the breakdown of what kind of liquids etc
                 variable,
                 ignore.case = TRUE, 
                 fixed = TRUE)) %>%
    # filter(between(period, 2025, 2070),
    filter(between(period, 2025, 2070),
           region == "World") %>%
    select(-model, -region) %>%
    group_by(period) %>%
    mutate(total_CO2_yearly = sum(value, na.rm = TRUE),
          total_CO2_5year = total_CO2_yearly * 5) %>%
    ungroup() %>%
    # comment below out if you want to have the full df
    select(scenario, unit, period, total_CO2_yearly, total_CO2_5year)
}

# List of data frames
# df_list <- list(df1 = df1, df2 = df2, df3 = df3, df4 = df4)
df_list <- list(df1 = early_trans, df2 = prolonged_lockin, df3 = extended_lockin, df4 = statusquo)
# Apply filtering to all data frames
filtered_dfs <- lapply(df_list, filter_mifdata)

#remove duplicates (only if not wanting the aggregate data)
filtered_dfs <- lapply(filtered_dfs, distinct)

# Extract results
early_trans_filtered <- filtered_dfs$df1
prolonged_lockin_filtered <- filtered_dfs$df2
extended_lockin_filtered <- filtered_dfs$df3
statusquo_filtered <- filtered_dfs$df4

early_trans_filtered <- early_trans_filtered %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  mutate(across(scenario, str_replace,"SteelCapBound-PkBudg650" ,"Early Transition Pathway (Low Lock-In)"))

prolonged_lockin_filtered <- prolonged_lockin_filtered %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  mutate(across(scenario, str_replace,"SteelCapBoundNoRetiReliningGovTarget-PkBudg650" ,"Prolonged Fossil-Steel Lock-In"))

extended_lockin_filtered <- extended_lockin_filtered %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  mutate(across(scenario, str_replace,"SteelCapBoundNoRetiRelining-PkBudg650" ,"Extended Fossil Dependence"))

statusquo_filtered <- statusquo_filtered %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  mutate(across(scenario, str_replace,"SteelCapBoundNoReti-PkBudg650" ,"Status Quo Lock-In"))


RIKEN_df <- bind_rows(early_trans_filtered, prolonged_lockin_filtered, extended_lockin_filtered, statusquo_filtered)
RIKEN_df_cumuCO2 <- RIKEN_df %>%
  group_by(scenario) %>%
  summarise(cumu_CO2 = max(cumu_CO2))
```
```{r pot em global, echo = FALSE}
#adjust factors
RIKEN_df$scenario <- factor(RIKEN_df$scenario, levels = c("Early Transition Pathway (Low Lock-In)","Status Quo Lock-In", "Extended Fossil Dependence","Prolonged Fossil-Steel Lock-In"))
RIKEN_df_cumuCO2$scenario <- factor(RIKEN_df_cumuCO2$scenario, levels = c("Early Transition Pathway (Low Lock-In)","Status Quo Lock-In", "Extended Fossil Dependence", "Prolonged Fossil-Steel Lock-In"))


#BOSCH talk colors
custom_colors <- c(
  "Early Transition Pathway (Low Lock-In)" = "#7BADAE",
  "Status Quo Lock-In" = "#6E8980",
  "Extended Fossil Dependence" = "#757A67",
  "Prolonged Fossil-Steel Lock-In" = "#8A704E"
)


ggplot(RIKEN_df_cumuCO2, 
                   aes(x = scenario, y = cumu_CO2/1e3, fill = scenario)) +
  geom_bar(stat = "identity", width = 0.8) +
  # scale_fill_viridis_d(option = "plasma", end = 0.9) +
  scale_fill_manual(values = custom_colors) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 15)) +
  labs(title = "Cumulative CO2 Emissions (2025-2070)\nfrom steel production, by scenario",
       x = "Scenario",
       y = "Cumulative CO2 (Gt CO2)") +
  theme_classic() +
  guides(fill="none")+
  scale_y_continuous(
    name = "Cumulative CO2 (Gt CO2)",
    # sec.axis = sec_axis(~ . * 0.00045, name = "Temperature Increase (°C)")
    sec.axis = sec_axis(~ ((. / 235)) * 100, name = "Fraction of remaining 1.5°C carbon budget (%)")
  ) +
    theme(
      #plot margin to combine as subfigure with lineplot below
    plot.margin = margin(5, 0, 14, 5),
    text = element_text(size = 7.5),
    title = element_text(size = 8),
    axis.title = element_text(size = 7.5),
    axis.text = element_text(size=7),
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.grid.major = element_line(linetype = "dashed", color = "gray70",
    )
  )
ggsave("RIKEN_cumuCO2.png", width = 79, height = 90.3, units = "mm", dpi = 300)

```

```{r plot line global, echo = FALSE}
RIKEN_df$scenario <- factor(RIKEN_df$scenario, levels = c("Early Transition Pathway (Low Lock-In)","Status Quo Lock-In", "Extended Fossil Dependence","Prolonged Fossil-Steel Lock-In"))

# Line plot for total_CO2_yearly over time, colored by scenario
ggplot(RIKEN_df, aes(x = period, y = total_CO2_yearly, color = scenario)) +
  geom_line(linewidth = 0.8) +
  geom_point(size = 1.5) +
  # scale_colour_discrete(labels = function(x) str_wrap(x, width = 10)) +
  scale_colour_viridis_d(option = "plasma", end = 0.9, 
                        labels = function(x) str_wrap(x, width = 22)) +
  labs(title = "a) Yearly Steel CO2 Emissions by scenario\n",
       x = "Year",
       y = "Yearly CO2 Emissions (Mt CO2/yr)") +
  theme_classic() +
  theme(
     plot.margin = margin(10, 10, 2, 10),
    text = element_text(size = 7.5),
    title = element_text(size = 8),
    legend.text = element_text(size = 6),
    legend.title = element_text(size = 6.5),
    axis.title = element_text(size = 7.5),
    axis.text = element_text(size=7),
    #axis.text.x = element_text(angle = 45, hjust = 1),
    legend.position = "bottom",
    legend.key.height = unit(2.5, "mm"),
    legend.key.width = unit(4, "mm"),
    legend.margin = margin(0, 0, 0, 0),
    legend.box = "horizontal",
    panel.grid.major = element_line(linetype = "dashed", color = "gray70")
  ) +
  guides(color = guide_legend(title = "Scenario", ncol = 2, 
                              byrow = TRUE, override.aes = list(size = 2)))

#save
#ggsave("RIKEN_yearlyCO2.png", width = 79, height = 90.3, units = "mm", dpi = 300)
```
```{r RIKEN test filter, echo = FALSE}

filter_mifdata_industryem <- function(df) {
  df %>%
    filter(grepl("Emi|CO2|Energy|Demand|Industry|++",
                # "Emi|CO2|Energy|Demand|Industry|Steel", # if we want the breakdown of what kind of liquids etc
                 variable,
                 ignore.case = TRUE, 
                 fixed = TRUE)) %>%
    # filter(between(period, 2020, 2060),
    filter(between(period, 2025, 2070),
          #  region == "World") %>%
          region %in% c("World", "IND", "CHA")) %>% 
    select(-model) %>%
    mutate(variable = gsub("Emi|CO2|Energy|Demand|Industry|\\+\\+|", "", variable)) %>%
    mutate(variable = gsub("\\|+", "", variable)) %>%
    mutate(variable = gsub(" ", "", variable)) %>%
    mutate(total_CO2_5year = value * 5)
    # # comment below out if you want to have the full df
    # select(scenario, unit, period, total_CO2_yearly, total_CO2_5year)
}

# List of data frames
df_list <- list(df1 = early_trans, df2 = prolonged_lockin, df3 = extended_lockin, df4 = statusquo)
# Apply filtering to all data frames
filtered_dfs <- lapply(df_list, filter_mifdata_industryem)

#remove duplicates (only if not wanting the aggregate data)
filtered_dfs <- lapply(filtered_dfs, distinct)

# Extract results
early_trans_em <- filtered_dfs$df1
prolonged_lockin_em <- filtered_dfs$df2
extended_lockin_em <- filtered_dfs$df3
statusquo_em <- filtered_dfs$df4

early_trans_em <- early_trans_em %>%
  group_by(variable, region) %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  ungroup() %>%
  mutate(across(scenario, str_replace,"SteelCapBound-PkBudg650" ,"Early Transition Pathway (Low Lock-In)"))

prolonged_lockin_em <- prolonged_lockin_em %>%
  group_by(variable, region) %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  ungroup() %>%
  mutate(across(scenario, str_replace,"SteelCapBoundNoRetiReliningGovTarget-PkBudg650" ,"Prolonged Fossil-Steel Lock-In"))

extended_lockin_em <- extended_lockin_em %>%
  group_by(variable, region) %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  ungroup() %>%
  mutate(across(scenario, str_replace,"SteelCapBoundNoRetiRelining-PkBudg650" ,"Extended Fossil Dependence"))

statusquo_em <- statusquo_em %>%
  group_by(variable, region) %>%
  mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  ungroup() %>%
  mutate(across(scenario, str_replace,"SteelCapBoundNoReti-PkBudg650" ,"Status Quo Lock-In"))


RIKEN_df <- bind_rows(early_trans_em, prolonged_lockin_em, extended_lockin_em, statusquo_em)
RIKEN_df_cumuCO2sectors <- RIKEN_df %>%
  group_by(scenario, region, variable) %>%
  summarise(cumu_CO2 = max(cumu_CO2)) %>%
  mutate(cumu_CO2 = cumu_CO2 / 1e3) # to GtCO2

RIKEN_df_cumuCO2sectorsglobal <- RIKEN_df_cumuCO2sectors %>%
  filter(region == "World")
```

```{r plot cumu em sectors, echo = FALSE}	

RIKEN_df_cumuCO2sectors$scenario <- factor(RIKEN_df_cumuCO2sectors$scenario, levels = c("Early Transition Pathway (Low Lock-In)","Status Quo Lock-In", "Extended Fossil Dependence", "Prolonged Fossil-Steel Lock-In"))
RIKEN_df_cumuCO2sectorsglobal$scenario <- factor(RIKEN_df_cumuCO2sectorsglobal$scenario, levels = c("Early Transition Pathway (Low Lock-In)","Status Quo Lock-In", "Extended Fossil Dependence", "Prolonged Fossil-Steel Lock-In"))

stacked_bar_plot <- ggplot(RIKEN_df_cumuCO2sectorsglobal, aes(x = scenario, y = cumu_CO2, fill = variable)) +
  geom_bar(stat = "identity", width = 0.6) +
  #scale_fill_viridis_d(option = "plasma", end = 0.9) +
  scale_fill_manual(values = c("Steel" = "#E68F00",
                              "Cement" = "#cdcccc",
                              "Chemicals" = "#9e9d9d",
                              "Other" = "#838282")) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 20)) +
  scale_y_continuous(
    name = "Cumulative CO2 (Gt CO2)",
    # sec.axis = sec_axis(~ . * 0.00045, name = "Temperature Increase (°C)")
    sec.axis = sec_axis(~ ((. / 650)) * 100, name = "Fraction of remaining 1.5°C carbon budget (%)")
  ) +
  labs(title = "Cumulative CO2 emissions by scenario, for all industry subsectors",
       x = "Scenario",
       y = "Cumulative CO2 (Gt CO2)") +
  theme_classic() +
  guides(fill = guide_legend(title = "Industry subsectors"))+
    theme(
    text = element_text(size = 14),
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.grid.major = element_line(linetype = "dashed", color = "gray70")
  )


# # ##OPTION1
# # Custom x-axis labels: Scenarios on a new line
# custom_labels <- function(x) {
#   x <- str_replace(x, "\\.", "\n")  # Replace "." with a new line (scenario below region)
#   return(x)
# }

# wrap_labels <- function(x) {
#   str_wrap(x, width = 25)  # Adjust width to fit multiple lines
# }

# RIKEN_df_cumuCO2sectors <- RIKEN_df_cumuCO2sectors %>%
#   mutate(region = factor(region, levels = c("World", "CHA", "IND")),
#          scenario = factor(scenario, levels = unique(scenario)))

# #scne label for annotation
# scenario_positions <- RIKEN_df_cumuCO2sectors %>%
#   group_by(scenario) %>%
#   summarize(mid_pos = mean(as.numeric(interaction(region, scenario))))  # Find mid x-position for each scenario


# stacked_bar_plot <- ggplot(RIKEN_df_cumuCO2sectors, aes(x = interaction(region, scenario), y = cumu_CO2, fill = variable)) +
#   geom_bar(stat = "identity", width = 0.6) +
#   scale_fill_manual(values = c("Steel" = "#E68F00",
#                                "Cement" = "grey70",  
#                                "Chemicals" = "grey50",  
#                                "Other" = "grey30")) +
#   scale_x_discrete(labels = rep(c("Global", "China", "India"), length(unique(RIKEN_df_cumuCO2sectors$scenario)))) +  
#   scale_y_continuous(
#      name = "Cumulative CO2 (Gt CO2)",
# #     # sec.axis = sec_axis(~ . * 0.00045, name = "Temperature Increase (°C)")
#      sec.axis = sec_axis(~ ((. / 650)) * 100, name = "Fraction of remaining 1.5°C carbon budget (%)")
#    ) +
#   labs(title = "Cumulative CO2 Emissions from 2020-2070",
#        x = element_blank(),
#        y = "Cumulative CO2 (Gt CO2)") +
#   theme_classic() +
#   guides(fill = guide_legend(title = "Industry subsectors")) +
#   theme(
#     text = element_text(size = 14),
#     legend.position = "top",
#     axis.text.x = element_text(angle = 0, hjust = 0.5),  # Keep labels readable
#     panel.grid.major = element_line(linetype = "dashed", color = "gray70"),
#     plot.margin = margin(20, 10, 50, 10)
#   ) +
#   # annotate("text", 
#   #          x = scenario_positions$mid_pos, 
#   #          y = -max(RIKEN_df_cumuCO2sectors$cumu_CO2) * 0.5,  # Lower annotation further
#   #          label = wrap_labels(scenario_positions$scenario), 
#   #          size = 4, fontface = "bold")+
#   coord_cartesian(clip = "off")
   
# for (i in seq_along(scenario_positions$scenario)) {
#   stacked_bar_plot <- stacked_bar_plot +
#     annotation_custom(
#       grob = textGrob(wrap_labels(scenario_positions$scenario[i]), 
#                       gp = gpar(fontsize = 10, fontface = "bold")),
#       xmin = scenario_positions$mid_pos[i] - 0.1,
#       xmax = scenario_positions$mid_pos[i] + 0.1,
#       ymin = -max(RIKEN_df_cumuCO2sectors$cumu_CO2) * 0.35,
#       ymax = -max(RIKEN_df_cumuCO2sectors$cumu_CO2) * 0.35
#      ) #+
#     # geom_segment(
#     #   aes(x = scenario_positions$mid_pos[i] - 1, xend = scenario_positions$mid_pos[i] + 1,
#     #       y = -max(RIKEN_df_cumuCO2sectors$cumu_CO2) * 0.8, yend = -max(RIKEN_df_cumuCO2sectors$cumu_CO2) * 0.8),
#     #   color = "black", size = 0.5
#     # )
# }

print(stacked_bar_plot)
#ggsave("C:/Users/claraba/Documents/PhD_work/Papers/SteelREMIND/AnalysisScript/RIKEN/RIKEN_cumuindustrysubsectors.png")#, width = 10, height = 6, units = "in", dpi = 300)
```

```{r check total CO2, echo = FALSE}
filter_mifdata <- function(df) {
  df %>%
    filter(grepl("Emi|CO2|Energy|Demand|Industry|Steel|+",
                # "Emi|CO2|Energy|Demand|Industry|Steel", # if we want the breakdown of what kind of liquids etc
                 variable,
                 ignore.case = TRUE, 
                 fixed = TRUE)) %>%
    # filter(between(period, 2025, 2070),
    filter(between(period, 2025, 2070),
           region == "World") %>%
    select(-model, -region) %>%
    group_by(period) %>%
    mutate(total_CO2_yearly = sum(value, na.rm = TRUE),
          total_CO2_5year = total_CO2_yearly * 5) %>%
    ungroup() 
    # %>%
    # # comment below out if you want to have the full df
    # select(scenario, unit, period, total_CO2_yearly, total_CO2_5year)
}

#filter to select variables containing Emi in early trans
test <- early_trans %>%
  # filter(grepl("Emi|GHG",
  #               variable,
  #               ignore.case = TRUE, 
  #               fixed = TRUE)) %>%
  # filter(variable == "Emi|GHG") %>%
  filter(variable == "Emi|CO2|Cumulated") %>%
  filter(between(period, 1995, 2100),
           region == "World")
  # select(-model, -region) %>%
  # group_by(period) %>%
  # mutate(total_CO2_yearly = sum(value, na.rm = TRUE),
  #         total_CO2_5year = total_CO2_yearly * 5) %>%
  # ungroup()%>%
  # group_by(variable) %>%
  # mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
  # ungroup() %>%
  # select(-unit)

test

# List of data frames
# df_list <- list(df1 = df1, df2 = df2, df3 = df3, df4 = df4)
df_list <- list(df1 = early_trans, df2 = prolonged_lockin, df3 = extended_lockin, df4 = statusquo)
# Apply filtering to all data frames
filtered_dfs <- lapply(df_list, filter_mifdata)

#remove duplicates (only if not wanting the aggregate data)
filtered_dfs <- lapply(filtered_dfs, distinct)

# Extract results
early_trans_filtered <- filtered_dfs$df1
prolonged_lockin_filtered <- filtered_dfs$df2
extended_lockin_filtered <- filtered_dfs$df3
statusquo_filtered <- filtered_dfs$df4
```