```{r setup, include = FALSE}
path <- "C:/Users/claraba/Documents/PhD_work/Papers/SteelREMIND/AnalysisScript/"
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(
    root.dir = path
    )

require(ggplot2)
require(tidyverse)
require(mrremind)
require(magclass)
require("quitte")

library("quitte")
library(dplyr)
library(gridExtra)
library(grid)
library(purrr)
```

```{r load data}
mifdata1 <- read.quitte("inputdata/mif/REMIND_generic_SteelCapBoundNoRetiReliningGovTarget-PkBudg650.mif")
mifdata2 <- read.quitte("inputdata/mif/REMIND_generic_PolicyExtended_expensiveH2-1-PkBudg650.mif")
mifdata3 <- read.quitte("inputdata/mif/REMIND_generic_PolicyExtended_expensiveH2-2-PkBudg650.mif")

mifdata4 <- read.quitte("inputdata/mif/REMIND_generic_PolicyExtended_moreCCS-PkBudg650.mif")
mifdata5 <- read.quitte("inputdata/mif/REMIND_generic_PolicyExtended_moreBFCCS-PkBudg650.mif")
mifdata6 <- read.quitte("inputdata/mif/REMIND_generic_PolicyExtended_moreCCS_BFCCSEarlyReti-PkBudg650.mif")

#other lock in scenarios
mifdata7 <- read.quitte("inputdata/mif/REMIND_generic_SteelCapBound-PkBudg650.mif")
mifdata8 <- read.quitte("inputdata/mif/REMIND_generic_SteelCapBoundNoReti-PkBudg650.mif")
mifdata9 <- read.quitte("inputdata/mif/REMIND_generic_SteelCapBoundNoRetiRelining-PkBudg650.mif")

mifdata1 <- mifdata1 %>%
  mutate(scenario = "Base H2 cost")
  # mutate(scenario = "Policy Extended Transition")

mifdata2 <- mifdata2 %>%
  mutate(scenario = "High H2 cost")

mifdata3 <- mifdata3 %>%
  mutate(scenario = "Very high H2 cost")

mifdata4 <- mifdata4 %>%
  mutate(scenario = "More CCS injection capacity")

mifdata5 <- mifdata5 %>%
  mutate(scenario = "Early retirement of BF-BOF-CCS")

mifdata6 <- mifdata6 %>%
  mutate(scenario = "More CCS injection capacity +\nearly retirement of BF-BOF-CCS")

mifdata7 <- mifdata7 %>%
  mutate(scenario = "Early Transition")

mifdata8 <- mifdata8 %>%
  mutate(scenario = "Base Transition")

mifdata9 <- mifdata9 %>%
  mutate(scenario = "Extended Lifetime Transition")

```

```{r plot params, echo = FALSE}	

fs = 10 # font size

steel_route <- tribble(
  ~route,          ~route_name, ~color,
  "BF-BOF",         "BF-BOF",    "#080808",
  "BF-BOF-CCS",     "BF-BOF CCS",    "#a0a0a0",
  "DRI-NG-EAF-CCS", "DRI-EAF NG CCS",    "#8fd1af",
  "DRI-NG-EAF",     "DRI-EAF NG",    "#06b429",
  "DRI-H2-EAF",     "DRI-EAF H2",    "#17cff0",
  "SCRAP-EAF",        "Scrap EAF",   "#fbfb0d",
)
```

```{r change data, echo = FALSE}

mifdata_list <- list(mifdata1, mifdata2, mifdata3)
ccs_list <- list(mifdata1, mifdata4, mifdata5, mifdata6)

lockin_list <- list(mifdata1,mifdata7, mifdata8, mifdata9)

#filter breakdown of steel production
process_data <- function(df) {
  df %>%
    filter(grepl("Production|Industry|Steel|+", variable, ignore.case = TRUE, fixed = TRUE)) %>%
    filter(region == "World", unit == "Mt/yr") %>%
    filter(between(period, 2020, 2100)) %>%
    mutate(variable = gsub("Production|Industry|Steel|+", "", variable)) %>%
    mutate(variable = sub("^\\|\\|\\|\\+\\|", "", variable, fixed = FALSE)) 
    # %>%
    # filter(variable != "SCRAP-EAF") #remove secondary steel
}

process_data_ccs <- function(df) {
  df %>%
    filter(grepl("Production|Industry|Steel|+", variable, ignore.case = TRUE, fixed = TRUE)) %>%
    filter(between(period, 2020, 2100)) %>%
    mutate(variable = gsub("Production|Industry|Steel|+", "", variable)) %>%
    mutate(variable = sub("^\\|\\|\\|\\+\\|", "", variable, fixed = FALSE)) %>%
    filter(variable != "SCRAP-EAF") #remove secondary steel
}

process_data_lockin <- function(df) {
  df %>%
    filter(grepl("Production|Industry|Steel|+", variable, ignore.case = TRUE, fixed = TRUE)) %>%
    filter(region == "World", unit == "Mt/yr") %>%
    filter(between(period, 2020, 2100)) %>%
    mutate(variable = gsub("Production|Industry|Steel|+", "", variable)) %>%
    mutate(variable = sub("^\\|\\|\\|\\+\\|", "", variable, fixed = FALSE)) %>%
    filter(variable != "SCRAP-EAF") #remove secondary steel
}

#get full df
prsteel_df <- mifdata_list %>%
  map_dfr(process_data)

ccsscen_df <- ccs_list %>%
  map_dfr(process_data_ccs)

lockin_df <- lockin_list %>%
  map_dfr(process_data_lockin)

#calculate h2 shareh2_ in total primary steel
h2_share <- prsteel_df %>%
  group_by(period, scenario) %>%
  summarise(h2_share = sum(value[variable == "DRI-H2-EAF"]) / sum(value)) %>%
  mutate(h2_share = h2_share*100) #to percent

h2_all_steel_shares <- prsteel_df %>%
  group_by(period, scenario) %>%
  summarise(
    h2_share = sum(value[variable == "DRI-H2-EAF"]) / sum(value),
    scrap_eaf_share = sum(value[variable == "SCRAP-EAF"]) / sum(value),
    coal_based_share = sum(value[variable %in% c("BF-BOF", "BF-BOF-CCS")]) / sum(value)
  ) %>%
  mutate(
    h2_share = h2_share * 100,
    scrap_eaf_share = scrap_eaf_share * 100,
    coal_based_share = coal_based_share * 100
  )


h2_share_lockin <- lockin_df %>%
  group_by(period, scenario) %>%
  summarise(h2_share = sum(value[variable == "DRI-H2-EAF"]) / sum(value)) %>%
  mutate(h2_share = h2_share*100) #to percent

#calculate amount of H2 dri
h2_dri <- prsteel_df %>%
  filter(variable == "DRI-H2-EAF") %>%
  group_by(period, scenario) %>%
  summarise(value = sum(value))

ccs_share <- ccsscen_df %>%
  group_by(period, scenario, region) %>%
  summarise(ccs_share = sum(value[variable == "BF-BOF-CCS"]) / sum(value)) %>%
  mutate(ccs_share = ccs_share*100) #to percent

all_steel_shares <- ccsscen_df %>%
  group_by(period, scenario, region) %>%
  summarise(
    total_production = sum(value, na.rm = TRUE),
    h2_share = sum(value[variable == "DRI-H2-EAF"], na.rm = TRUE) / total_production,
    bf_bof_ccs_share = sum(value[variable == "BF-BOF-CCS"], na.rm = TRUE) / total_production,
    bf_bof_share = sum(value[variable == "BF-BOF"], na.rm = TRUE) / total_production,
    ng_share = sum(value[variable == "DRI-NG-EAF"], na.rm = TRUE) / total_production
  )


```

```{r calc cumu em}
calc_cumuem <- function(df) {
  df %>%
    filter(grepl("Emi|CO2|Energy|Demand|Industry|Steel|+",
                # "Emi|CO2|Energy|Demand|Industry|Steel", # if we want the breakdown of what kind of liquids etc
                 variable,
                 ignore.case = TRUE, 
                 fixed = TRUE)) %>%
    # filter(between(period, 2025, 2070),
    filter(between(period, 2025, 2100),
           region == "World") %>%
    select(-model, -region) %>%
    #add up the different components: solid, liquids ..
    group_by(period, scenario) %>%
    summarise(total_CO2_yearly = sum(value, na.rm = TRUE),
          total_CO2_5year = total_CO2_yearly * 5) %>%
    ungroup() %>%
    group_by(scenario) %>%
    mutate(cumu_CO2 = cumsum(total_CO2_5year)) %>%
    summarise(cumu_CO2 = max(cumu_CO2))
}

ccsscen_emi_df <- ccs_list %>%
  map_dfr(calc_cumuem) 

```


```{r plot h2 share, echo = FALSE}

h2_share_plot <- h2_share

#factors for scenarios
# h2_share_plot$scenario <- factor(h2_share_plot$scenario, levels = c("Base H2 cost", "High H2 cost", "Very high H2 cost"))


#make line plot of h2 share, one line for each scenario

ggplot(h2_share_plot, aes(x = period, y = h2_share, color = scenario)) +
  geom_line(size = 0.6, alpha = 0.8) +
  geom_point(size = 2, shape = 21, fill = "white", stroke = 0.8) +
  labs(title = "Share of DRI-H2-EAF in total steel production",
       x = "Time",
       y = "DRI-H2-EAF share (%)",
       color = "Scenario") +
  # scale_color_viridis_d(option = "C") +
  scale_color_manual(values = c("#0d55c9", "#22cdbc", "#8586bc", "#3d3d3f","#8d8d92", "#41415d")) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", hjust = 0.5),
    axis.title = element_text(face = "bold")
  ) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE))

#save
# ggsave("figs/h2_share.png", width = 8, height = 5, dpi = 300)
```

```{r plot h2 scen all steel shares, echo = FALSE}

h2_all_steel_shares_long <- h2_all_steel_shares %>%
  pivot_longer(
    cols = c("h2_share", "scrap_eaf_share", "coal_based_share"),
    names_to = "steel_type",
    values_to = "share"
  )

h2_all_steel_shares_long <- h2_all_steel_shares_long %>%
  mutate(steel_type = recode(steel_type,
                             h2_share = "Hydrogen-based steel\n(DRI-H2-EAF)",
                             scrap_eaf_share = "Secondary steel\n(Scrap EAF)",
                             coal_based_share = "Coal-based steel production\n(BF-BOF-CCS + BF-BOF)"))

ggplot(h2_all_steel_shares_long, aes(x = period, y = share, color = scenario)) +
  geom_line(size = 0.6, alpha = 0.8) +
  geom_point(size = 2, shape = 21, fill = "white", stroke = 0.8) +
  labs(
    title = "Steel production shares by production route",
    x = "Time",
    y = "Share (%)",
    color = "Scenario"
  ) +
  scale_color_manual(values = c("#0d55c9", "#22cdbc", "#8586bc", "#3d3d3f", "#8d8d92", "#41415d")) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", hjust = 0.5),
    axis.title = element_text(face = "bold")
  ) +
  guides(color = guide_legend(nrow = 1, byrow = TRUE)) +
  facet_wrap(~ steel_type)

#save
# ggsave("figs/h2scenarios_all_steel_shares.png", width = 8, height = 5, dpi = 300)
```
```{r plot h2 share lockin scen, echo = FALSE}

# h2_share_plot <- h2_share_lockin

#factors for scenarios
# h2_share_plot$scenario <- factor(h2_share_plot$scenario, levels = c("Base H2 cost", "High H2 cost", "Very high H2 cost"))


#make line plot of h2 share, one line for each scenario

ggplot(h2_share_lockin, aes(x = period, y = h2_share, color = scenario)) +
  geom_line(size = 0.6, alpha = 0.8) +
  geom_point(size = 2, shape = 21, fill = "white", stroke = 0.8) +
  labs(title = "Share of DRI-H2-EAF in primary steel production",
       x = "Time",
       y = "DRI-H2-EAF share (%)",
       color = "Scenario") +
  # scale_color_viridis_d(option = "C") +
  scale_color_manual(values = c("#7BADAE", "#6E8980", "#757A67", "#8A704E")) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", hjust = 0.5),
    axis.title = element_text(face = "bold")
  ) +
  guides(color = guide_legend(nrow = 2, byrow = TRUE))

#save
# ggsave("figs/h2_share_lockin.png", width = 8, height = 5, dpi = 300)
```


```{r plot ccs cumu emi}
# Copy the data
ccsscen_emi_df_plot <- ccsscen_emi_df

# Rename "Base H2 cost" to "Base CCS assumption"
ccsscen_emi_df_plot$scenario <- gsub("Base H2 cost", "Base CCS assumption", ccsscen_emi_df_plot$scenario)

# Get unique scenario names
unique_scenarios <- unique(ccsscen_emi_df_plot$scenario)

# Convert to factor
ccsscen_emi_df_plot$scenario <- factor(ccsscen_emi_df_plot$scenario, levels = unique_scenarios)

# Define colors
custom_colors <- c(
  "Base CCS assumption" = "#8A704E",
  "More CCS injection capacity" = "#b09105",
  "Early retirement of BF-BOF-CCS" = "#bf6e12",
  "More CCS injection capacity +\nearly retirement of BF-BOF-CCS" = "#e6c90e"
)

# Compute percentage difference
base_value <- ccsscen_emi_df_plot %>%
  filter(scenario == "Base CCS assumption") %>%
  pull(cumu_CO2) / 1e3  # Convert to same units

ccsscen_emi_df_plot <- ccsscen_emi_df_plot %>%
  mutate(percentage_diff = ifelse(scenario == "Base CCS assumption", 
                                  NA, 
                                  ((cumu_CO2 / 1e3 - base_value) / base_value) * 100))

# Find x-coordinates of bars
x_base <- which(levels(ccsscen_emi_df_plot$scenario) == "Base CCS assumption")
x_others <- which(levels(ccsscen_emi_df_plot$scenario) != "Base CCS assumption")

# Find y-coordinates for arrows
y_base <- base_value + 30  # Slightly above base bar
y_others <- ccsscen_emi_df_plot$cumu_CO2[ccsscen_emi_df_plot$scenario != "Base CCS assumption"] / 1e3 + 30

# Plot
ggplot(ccsscen_emi_df_plot, aes(x = scenario, y = cumu_CO2 / 1e3, fill = scenario)) +
  geom_bar(stat = "identity", width = 0.6) +
  scale_fill_manual(values = custom_colors) +
  scale_x_discrete(labels = function(x) str_wrap(x, width = 20)) +
  labs(
    title = "Cumulative CO2 Emissions (2025-2070)\nfrom steel production, by scenario",
    x = "Scenario",
    y = "Cumulative CO2 (Gt CO2)"
  ) +
  theme_classic() +
  guides(fill = "none") +
  scale_y_continuous(
    name = "Cumulative CO2 (Gt CO2)",
    sec.axis = sec_axis(~ ((. / 235)) * 100, name = "Fraction of remaining 1.5°C carbon budget (%)")
  ) +
  theme(
    text = element_text(size = 10),
    title = element_text(size = 12),
    axis.title = element_text(size = 11),
    axis.text = element_text(size = 10),
    axis.text.x = element_text(angle = 0, hjust = 0.5),
    panel.grid.major = element_line(linetype = "dashed", color = "gray70")
  ) +
  # Add arrows from Base CCS assumption to other bars
  geom_segment(aes(x = x_base, xend = x_base, y = base_value, yend = y_base), 
               color = "#7e7e7e") +
  geom_segment(aes(x = x_base, xend = x_others[3], y = y_base, yend = y_base), 
               color = "#7e7e7e") +
  geom_segment(aes(x = x_others[1], xend = x_others[1], y = y_base, yend = y_others[1]-30),
               arrow = arrow(type = "closed", length = unit(0.15, "inches")), color = "#7e7e7e") +
  geom_segment(aes(x = x_others[2], xend = x_others[2], y = y_base, yend = y_others[2]-30),
               arrow = arrow(type = "closed", length = unit(0.15, "inches")), color = "#7e7e7e") +
  geom_segment(aes(x = x_others[3], xend = x_others[3], y = y_base, yend = y_others[3]-30),
               arrow = arrow(type = "closed", length = unit(0.15, "inches")), color = "#7e7e7e") +

  # Add white circles behind percentage difference labels
  geom_point(aes(x = x_base*2, y = (y_base) / 2 + 35),
             shape = 21, fill = "white", color = "#7e7e7e", size = 15) +
  geom_point(aes(x = x_base*3, y = (y_base) / 2 + 35),
             shape = 21, fill = "white", color = "#7e7e7e", size = 15) +
  geom_point(aes(x = x_base*4, y = (y_base) / 2 + 30),
             shape = 21, fill = "white", color = "#7e7e7e", size = 15) +
  # Add percentage difference labels above arrows
  annotate("text", x = (x_base*2), y = (y_base) / 2 + 35,
           label = paste0(round(ccsscen_emi_df_plot$percentage_diff[2], 1), "%"), size = 3, fontface = "bold", color = "#7e7e7e") +
  annotate("text", x = (x_base *3), y = y_base/ 2 + 35,
           label = paste0(round(ccsscen_emi_df_plot$percentage_diff[3], 1), "%"), size = 3, fontface = "bold", color = "#7e7e7e") +
  annotate("text", x = (x_base *4), y = (y_base ) / 2 +30,
           label = paste0(round(ccsscen_emi_df_plot$percentage_diff[4], 1), "%"), size = 3, fontface = "bold", color = "#7e7e7e")

#save
# ggsave("figs/cumu_emi_ccs_scen.png", width = 8, height = 5, dpi = 300)

```

```{r plot ccs share, echo = FALSE}

ccs_share_glob <- ccs_share %>%
  filter(region == "World") %>%
  select(-region)

#rename "base H2 cost" to "Base H2 cost"
ccs_share_glob$scenario <- gsub("Base H2 cost", "Base CCS assumption", ccs_share_glob$scenario)

#factors for scenarios
ccs_share_glob$scenario <- factor(ccs_share_glob$scenario, levels = c("Base CCS assumption", "More CCS injection capacity","Early retirement of BF-BOF-CCS", "More CCS injection capacity +\nearly retirement of BF-BOF-CCS"))

#plot
ggplot(ccs_share_glob, aes(x = period, y = ccs_share, color = scenario)) +
  geom_line(size = 0.6, alpha = 1) +
  geom_point(size = 2, shape = 21, fill = "white", stroke = 0.8) +
  labs(title = "Share of BF-BOF-CCS in total primary steel production (World)",
       x = "Time",
       y = "BF-BOF-CCS share (%)",
       color = "Scenario") +
  scale_color_viridis_d(option = "inferno", end = 0.8, direction = -1) +
  #scale_color_manual(values = c("#c6c9cd", "#928166", "#8d5252", "#000000")) +
  #add y limit
  ylim(0, 100) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", hjust = 0.5),
    axis.title = element_text(face = "bold")
  )+
  guides(color = guide_legend(nrow = 2, byrow = TRUE))

#save
# ggsave("figs/ccs_share_global.png", width = 8, height = 5, dpi = 300)
```

```{r plot ccs share, echo = FALSE}

ccs_share_IND <- ccs_share %>%
  filter(region == "IND") %>%
  select(-region)

#rename "base H2 cost" to "Base H2 cost"
ccs_share_IND$scenario <- gsub("Base H2 cost", "Base CCS assumption", ccs_share_IND$scenario)

#factors for scenarios
ccs_share_IND$scenario <- factor(ccs_shar_INDe$scenario, levels = c("Base CCS assumption", "More CCS injection capacity","Early retirement of BF-BOF-CCS", "More CCS injection capacity +\nearly retirement of BF-BOF-CCS"))

#plot
ggplot(ccs_share_IND, aes(x = period, y = ccs_share, color = scenario)) +
  geom_line(size = 0.6, alpha = 1) +
  geom_point(size = 2, shape = 21, fill = "white", stroke = 0.8) +
  labs(title = "Share of BF-BOF-CCS in total primary steel production (India)",
       x = "Time",
       y = "BF-BOF-CCS share (%)",
       color = "Scenario") +
  scale_color_viridis_d(option = "inferno", end = 0.8) +
  #scale_color_manual(values = c("#c6c9cd", "#928166", "#8d5252", "#000000")) +
  theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", hjust = 0.5),
    axis.title = element_text(face = "bold")
  )+
  guides(color = guide_legend(nrow = 2, byrow = TRUE))

```

```{r plot ccs share, echo = FALSE}

ccs_share_CHA <- ccs_share %>%
  filter(region == "CHA") %>%
  select(-region)

#rename "base H2 cost" to "Base H2 cost"
ccs_share_CHA$scenario <- gsub("Base H2 cost", "Base CCS assumption", ccs_share_CHA$scenario)

#factors for scenarios
ccs_share_CHA$scenario <- factor(ccs_share_CHA$scenario, levels = c("Base CCS assumption", "More CCS injection capacity","Early retirement of BF-BOF-CCS", "More CCS injection capacity +\nearly retirement of BF-BOF-CCS"))

#plot
ggplot(ccs_share_CHA, aes(x = period, y = ccs_share, color = scenario)) +
  geom_line(size = 0.6, alpha = 1) +
  geom_point(size = 2, shape = 21, fill = "white", stroke = 0.8) +
  labs(title = "Share of BF-BOF-CCS in total primary steel production (China)",
       x = "Time",
       y = "BF-BOF-CCS share (%)",
       color = "Scenario") +
  scale_color_viridis_d(option = "inferno", end = 0.8, direction = -1) +
  #scale_color_manual(values = c("#c6c9cd", "#928166", "#8d5252", "#000000")) +
  # theme_minimal(base_size = 14) +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 11),
    plot.title = element_text(face = "bold", hjust = 0.5),
    axis.title = element_text(face = "bold")
  )+
  guides(color = guide_legend(nrow = 2, byrow = TRUE))

#save
# ggsave("figs/ccs_share_oas.png", width = 8, height = 5, dpi = 300)
```

```{r plot ccs area plots, echo = FALSE}

plot_df <- all_steel_shares %>%
  filter(region == "World") %>%
  select(-total_production) %>%  # Remove unnecessary column
  pivot_longer(cols = ends_with("_share"), 
               names_to = "steel_route", 
               values_to = "share")  # Convert to long format for ggplot

plot_df$scenario <- gsub("Base H2 cost", "Base CCS assumption", plot_df$scenario)

# Improve steel_route labels
plot_df$steel_route <- recode(plot_df$steel_route,
                              "h2_share" = "DRI-H2-EAF",
                              "bf_bof_ccs_share" = "BF-BOF-CCS",
                              "bf_bof_share" = "BF-BOF",
                              "ng_share" = "DRI-NG-EAF")

plot_df <- plot_df %>%
  left_join(steel_route, by = c("steel_route" = "route"))

plot_df$steel_route <- factor(plot_df$steel_route, 
                              levels = c( "DRI-NG-EAF", "DRI-H2-EAF","BF-BOF-CCS","BF-BOF"))

color_mapping <- setNames(plot_df$color, plot_df$steel_route)

# COMBINED PLOT


# # Create a new column for the combined share of BF-BOF and BF-BOF CCS
plot_df <- plot_df %>%
  group_by(period, scenario) %>%
  mutate(combined_bf_bof_share = sum(share[steel_route %in% c("BF-BOF", "BF-BOF-CCS")])) %>%
  ungroup()


#COMBINE area plots
unique_scenarios <- unique(plot_df$scenario)

custom_linetypes <- c(
  "solid" = "solid",
  "dashed" = "44",
  "dotted" = "11",
  "dotdash" = "331331"
)

# Plot
ggplot() +
  geom_area(data = plot_df %>% filter(scenario == unique_scenarios[1]),
            aes(x = period, y = share, fill = steel_route), alpha = 0.25) +
  geom_area(data = plot_df %>% filter(scenario == unique_scenarios[2]),
            aes(x = period, y = share, fill = steel_route), alpha = 0.25) +
  geom_area(data = plot_df %>% filter(scenario == unique_scenarios[3]),
            aes(x = period, y = share, fill = steel_route), alpha = 0.25) +
  geom_area(data = plot_df %>% filter(scenario == unique_scenarios[4]),
            aes(x = period, y = share, fill = steel_route), alpha = 0.25) +
  scale_fill_manual(values = color_mapping) +
  labs(title = "Primary steel production share by pathway, for four CCS scenarios",
       x = "Year",
       y = "Share",
       fill = "Production pathway") +
  scale_y_continuous(labels = scales::percent_format(), expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) +
  # Overlay lines showing combined BF-BOF + BF-BOF CCS share with scenario-dependent linetype
  # geom_line(data = plot_df,
  #           aes(x = period, y = combined_bf_bof_share, group = scenario, color = scenario, linetype = scenario),
  #           size = 1.2) +
  # # Overlay lines showing BF-BOF share with scenario-dependent linetype
  geom_line(data = plot_df %>% filter(steel_route == "BF-BOF"),
            aes(x = period, y = share, group = scenario, linetype = scenario), #used to have  color = scenario,
            color = "#eadede",
            size = 1.2) +
  #scale_color_manual(name = "Scenario", values = setNames(c("#010101", "#ff6200", "#cb0ece", "#ffffff"), unique_scenarios)) +
  # scale_linetype_manual(name = "Scenario", values = setNames(c("solid", "dashed", "dotted", "dotdash"), unique_scenarios)) +
  scale_linetype_manual(name = "Scenario", values = setNames(custom_linetypes, unique_scenarios)) +
  guides(
    linetype = guide_legend(
      title = "Line Type",
      override.aes = list(size = 1)
    )
  ) +
  theme(
    # legend.background = element_rect(fill = "#a4a0a0", color = "white"),
    legend.key = element_rect(fill = "#b5b1b1", color = "white"),
    legend.key.size = unit(30, "points"),
    legend.spacing.x = unit(40, "points"),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10),
    axis.title.x = element_text(size = 13),
    axis.title.y = element_text(size = 13),
    axis.text = element_text(size = 12),
    plot.title = element_text(size = 14),
    )
#save
# ggsave("figs/areaplot_shares_ccs.png", width = 8, height = 5, dpi = 300)
```