```{r setup, include = FALSE}
path <- "C:/Users/claraba/Documents/PhD_work/Papers/SteelREMIND/Analysis/"
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(
    root.dir = path
    )


library(ggplot2)
library(gdx)
require(dplyr)
options(dplyr.summarise.inform = FALSE)
library(tidyr)
library(quitte)
library(lusweave)
library(ggsci)
library(pals)
library(stringr)
```

```{R init sets}


###################################################
# CONFIG

name <- "Policy-extended fossil lock-in"


#plotted_years <- c(2030, 2040, 2050)

plotted_regions <- c('EUR', 'CHA', 'USA', 'IND', 'GLO') 
fs = 10 # font size

route_names <- tribble(
  ~route,          ~route_name,
  "bfbof",         "BF-BOF",
  "bfbof_ccs",     "BF-BOF CCS",
  "idreaf_ng_ccs", "DRI-EAF NG CCS",
  "idreaf_ng",     "DRI-EAF NG",
  "idreaf_h2",     "DRI-EAF H2",
  "seceaf",        "Scrap EAF",
  "bfbof_ccs_r",   "BF-BOF CCS retrofit"
)

    
region_names  <- tribble(
  ~region, ~region_name,
  # 'JPN',   'Japan',
  # 'CAZ',   'Australia*'
  'EUR',   'EU',
  'CHA',   'China',
  'USA',   'USA',
  'IND',   'India',
  'GLO',   'Global'
)

```

We first calculate energy costs, using the prices, from which we first have to substract the CO2 price.

```{R load and calculate emiFac}	

calc_emfac <- function(gdx) {

  # emission factors are required to remove the CO2 price from the energy prices
  # these are available for all types of final energy, except electricity and hydrogen
  # for electricity and hydrogen, we need to calculate supply side emissions

  #load all emiFac (fe, se, pe)
  df.emiFac_all <- as.quitte(readGDX(gdx, name="pm_emifac", restore_zeros = F)) %>% 
    filter(all_enty2 == "co2", period %in% t)

  # save the Fe for now
  df.emiFacFe <- df.emiFac_all %>% 
    filter(all_enty1 %in% entyFE) %>%
    select(period, region, all_enty, all_enty1, value) %>%
    rename(entySE = all_enty, entyFE = all_enty1, emiFac = value)

  ### EMI FAC ELEC
  # calculate the emiFac for electricity from the supply side emissions
  # this requires PE emission factors and calculating the PE demand for electricity production

  pe2se <- readGDX(gdx, name="pe2se")

  #emifac for seel
  emifac_seel <- df.emiFac_all %>%
    filter(all_te %in% pe2se$all_te, all_enty1 == "seel") %>%
    select(region, period, value, all_enty, all_te) %>%
    rename(emiFac = value) %>%
    mutate(emiFac = if_else(is.na(emiFac), 0., emiFac))

  #get PE demand for seel
  vm_demPe_seel <- as.quitte(readGDX(gdx, "vm_demPE", field = "l", restore_zeros = F)) %>%
    filter(all_enty1 == "seel", period %in% t) %>%
    select(region, period, all_enty, all_te, value) %>%
    rename(demPe = value)

  #get total SE electricity production
  df.prodSe <- as.quitte(readGDX(gdx, "vm_prodSe", field = "l", restore_zeros = F)) %>%
    filter(all_enty1 == "seel", period %in% t) %>%
    group_by(region, period) %>%
      summarise(prodSe = sum(value)) %>%
      ungroup()

  df_emiPe_seel <- vm_demPe_seel %>%
    left_join(emifac_seel, by=c("region", "period", "all_enty", "all_te")) %>%
    mutate(emiFac = if_else(is.na(emiFac), 0., emiFac)) %>% #change renewables emission factor to 0
    mutate(emiPe = ifelse(demPe != 0, demPe * emiFac, 0.)) %>%
    group_by(region, period) %>%
    summarise(emiPetotal = sum(emiPe)) %>%
      ungroup() %>%
      #add the production of seel to calculate the emission factor
      left_join(df.prodSe, by=c("region", "period")) %>%
      mutate(emiFac = ifelse(prodSe != 0, emiPetotal/prodSe, 0.)) %>%
      select(region, period, emiFac) %>%
      mutate(entyFE = "feels", entySE = "seel")

  ### EMI FAC H2
  # calculate the emiFac for electricity from the supply side emissions
  # this requires PE emission factors and calculating the PE demand for h2 production
  # TODO: likely h2 emission factor also requires elec emiFac

  #emifac for h2
  emifac_h2 <- df.emiFac_all %>%
    filter(all_te %in% pe2se$all_te, all_enty1 == "seh2") %>%
    select(region, period, value, all_enty, all_te) %>%
    rename(emiFac = value) %>%
    mutate(emiFac = if_else(is.na(emiFac), 0., emiFac))

  #get PE demand for h2
  vm_demPe_h2 <- as.quitte(readGDX(gdx, "vm_demPE", field = "l", restore_zeros = F)) %>%
    filter(all_enty1 == "seh2", period %in% t) %>%
    select(region, period, all_enty, all_te, value) %>%
    rename(demPe = value)

  #get total SE h2 production
  df.prodSe <- as.quitte(readGDX(gdx, "vm_prodSe", field = "l", restore_zeros = F)) %>%
    filter(all_enty1 == "seh2", period %in% t) %>%
    group_by(region, period) %>%
      summarise(prodSe = sum(value)) %>%
      ungroup()

  df_emiPe_h2 <- vm_demPe_h2 %>%
    left_join(emifac_h2, by=c("region", "period", "all_enty", "all_te")) %>%
    mutate(emiFac = if_else(is.na(emiFac), 0., emiFac)) %>% #change renewables emission factor to 0
    mutate(emiPe = ifelse(demPe != 0, demPe * emiFac, 0.)) %>%
    group_by(region, period) %>%
    summarise(emiPetotal = sum(emiPe)) %>%
      ungroup() %>%
      #add the production of h2 to calculate the emission factor
      left_join(df.prodSe, by=c("region", "period")) %>%
      mutate(emiFac = ifelse(prodSe != 0, emiPetotal/prodSe, 0.)) %>%
      select(region, period, emiFac) %>%
      mutate(entyFE = "feh2s", entySE = "seh2")

  # combine elec emiFac with the other (FE) emifac
  # not used anymore
  # df.emiFac <- df.emiFacFe %>%
  #   bind_rows(df_emiPe_seel) %>%
  #   bind_rows(df_emiPe_h2)

  #in new code version, we use SE prices, which means we only need the emission factors of elec
  # TODO: add h2 emi fac calculated from elec emi fac and electrolysis efficiency
  df.emiFac <- df_emiPe_seel
  return(df.emiFac)
}
```

```{R calc t&d costs}
#creates function to calculate transmission and distribution costs
# these are only needed for when energy prices are calculated without a Co2 price 
# using SE prices, which do not include t&d costs

calc_td_costs <- function(gdx, df.priceFuel) {

  se2fe <- readGDX(gdx, name="se2fe") %>%
    rename(entySE = all_enty, entyFE = all_enty1, te_td = all_te)

  df.priceFuel <- df.priceFuel %>%
    left_join(se2fe, by=c("entySE","entyFE"))

  td_list <- unique(df.priceFuel$te_td)

  df.capFac <- as.quitte(readGDX(gdx, "vm_capFac", field="l", restore_zeros = F)[,t,]) %>%
      select(region, period, all_te, value) %>%
      filter(all_te %in% td_list ) %>%
      rename(capFac = value)

  wacc <- 0.05

  lifetime <- as.quitte(readGDX(gdx, name="fm_dataglob", restore_zeros = F)[,,"lifetime"][,,][,,"lifetime"]) %>% 
    filter(all_te %in% td_list)

  df.discFac <- lifetime %>%
    select(all_te, value) %>%
    rename(lifetime = value) %>%
    mutate( discFac = wacc * (1+wacc)^lifetime/(-1.+(1+wacc)^lifetime)) %>%
    select(all_te, discFac)

  df.CAPEX <- as.quitte(readGDX(gdx, "vm_costTeCapital", field = "l", restore_zeros = F)[,t,]) %>%
      filter(all_te %in% td_list) %>%
      select(region, period, all_te, value) %>%
      left_join(df.capFac, by=c("region", "period", "all_te")) %>%
      mutate(value = value / capFac) %>%  # conversion from MW/a to MWh/a
      select(-capFac)

  df.OPEX <- as.quitte(readGDX(gdx, "pm_data", restore_zeros = F)[,,"omf"]) %>%
      select(region, all_te, value) %>%
      filter(all_te %in% td_list, value > 0.) %>%
      full_join(df.CAPEX %>% 
                  rename(CAPEX = value) %>%
                  select(region, period, all_te, CAPEX),
                by=c("region", "all_te")) %>%
      mutate(OPEX = value * CAPEX ) %>% 
      select(-CAPEX, -value)
    
  # multiply with discount factor (has to be done after calculating OPEX)
  df.CAPEX <- df.CAPEX %>% 
    left_join(df.discFac, by="all_te") %>% 
    mutate(CAPEX = value * discFac) %>% 
    select(-discFac, -value)

  # eta, transmission efficiency
  df.eta <- as.quitte(readGDX(gdx, "pm_data", restore_zeros = F)[,,"eta"]) %>%
      select(region, all_te, value) %>%
      filter(all_te %in% td_list, value > 0.) %>%
      rename(eta = value)

  df.td_costs <- df.CAPEX %>%
    full_join(df.OPEX, by=c("region", "period", "all_te")) %>%
    left_join(df.eta, by=c("region", "all_te")) %>%
    mutate(td_costs = (CAPEX + OPEX) ) %>%
    select(region, period, all_te, td_costs, eta) %>%
    rename(te_td = all_te)


  df.priceFuel <- df.priceFuel %>%
    left_join(df.td_costs, by=c("region", "period", "te_td")) %>%
    # here, we assume transmission costs are given in terms of incoming energy
    # which means we divide the full price (SEprice + t&d costs) by the efficiency (eta)
    mutate(priceSEtd = (priceSE + td_costs) / eta) %>%
    select(-te_td, -td_costs, -eta, -priceSE) %>%
    #some SE prices have no corresponding FE demand for industry (seliqsyn, sehe, segasyn). remove them
    mutate(priceFuel = priceSEtd * replace_na(SEShare, 0.)) %>% 
    group_by(region, period, entyFE) %>% 
    summarize(priceFuel = sum(priceFuel)) %>%
    ungroup()

  #add FE tax and subsidies

  df.fetax <- as.quitte(readGDX(gdx, name="p21_tau_fe_tax", restore_zeros = F)) %>%
  filter(emi_sectors == "indst", value != 0. ) %>%
  select(region, period, value, all_enty) %>%
  rename(fe_tax = value)

  df.fesub <- as.quitte(readGDX(gdx, name="p21_tau_fe_sub", restore_zeros = F)) %>%
    filter(emi_sectors == "indst", value != 0. ) %>%
    select(region, period, value, all_enty) %>%
    rename(fe_sub = value)

  df.finalfetax <- df.fetax %>%
    full_join(df.fesub, by=c("region", "period", "all_enty")) %>%
    mutate(fe_tax = ifelse(is.na(fe_tax), 0., fe_tax),
          fe_sub = ifelse(is.na(fe_sub), 0., fe_sub)) %>%
    mutate(fe_tax_final = fe_tax + fe_sub) %>%
    select(region, period, all_enty, fe_tax_final) %>%
    rename(entyFE = all_enty)

  df.priceFuel <- df.priceFuel %>%
    left_join(df.finalfetax, by=c("region", "period", "entyFE")) %>%
    mutate(fe_tax_final = ifelse(is.na(fe_tax_final), 0., fe_tax_final),
            priceFuel = priceFuel + fe_tax_final) %>%
    select(-fe_tax_final)

  return(df.priceFuel)
}

```
```{R calculate energy demand and prices}

#calculates energy costs and demand based on a given gdx. 
# can include or exclude co2 price

calc_energy_costs <- function(gdx, include_co2_price = TRUE) {

  # CARBON COST: Carbon price times average emission per FE (which is determined by SE shares, i.e. fossil/bio/synfuel)

  df.priceCO2 <- as.quitte(readGDX(gdx,name=c("p_priceCO2","pm_priceCO2"),format="first_found")) %>%
      select(region, period, value) %>%
      # where carbon price is NA, it is zero
      mutate(value = ifelse(is.na(value), 0, value /1000.)) %>% # carbon price i given in $/tC instead of remind units (tn $/GtC)
      filter(period %in% t) %>%
      rename(priceCO2 = value)

  df.demFe <- as.quitte(readGDX(gdx, "vm_demFeSector_afterTax", field = "l", restore_zeros = F)[,t,]) %>%
    # dimensions: vm_demFeSector_afterTax(ttot,regi,entySE,entyFE,"indst",emiMkt)
    filter(all_enty1 %in% entyFE, emi_sectors == "indst", all_emiMkt == "ETS", value > 0.) %>%
    select(period, region, all_enty, all_enty1, value) %>%
    rename(demFE = value, entySE = all_enty, entyFE = all_enty1)

  df.emiFac <- calc_emfac(gdx)
    
  df.emiFacAvg <- df.demFe %>% 
    left_join(df.emiFac, by=c("region", "period", "entySE", "entyFE")) %>%
    mutate(emiFac = if_else(is.na(emiFac), 0., emiFac), emiTot = demFE * emiFac) %>%
    group_by(period, region, entyFE) %>%
    summarise(emiTot = sum(emiTot), demFE = sum(demFE)) %>%
    ungroup() %>%
    filter(demFE > 0.) %>%
    mutate(emiFac = emiTot / demFE) %>%
    select(-emiTot, -demFE)

  # FE tax per unit of burnt FE (USD/GWa)
  df.FeEmiCost <- df.priceCO2 %>% 
    right_join(df.emiFacAvg, by=c("period", "region")) %>% 
    mutate(FeEmiCost = priceCO2 * emiFac) %>%
    select(-emiFac, -priceCO2)


  #### CALC FUEL PRICES: 
  # 1) include CO2 prices: take price differentiated by SE, then take weighted sum according to SE shares.

  # 2) exclude CO2 prices: take SE prices (which do not include t&d or fuel taxes). 
  # These have no CO2 price for solids, liquids, gases. For elec, subtract CO2 tax.
  if (include_co2_price) {
    df.priceFuel <- as.quitte(readGDX(gdx, "p_FEPrice_by_SE_Sector_EmiMkt", restore_zeros = F)) %>%
      filter(sector == "indst", emiMkt == "ETS", value > 0., period %in% t) %>%
      select(region, period, entySe, all_enty, value) %>%
      rename(entySE = entySe, entyFE = all_enty, priceFuel = value)

    df.demFETotal = df.demFe  %>% 
      group_by( region, period, entyFE) %>% 
      summarize(demFETotal = sum(demFE)) %>%
      ungroup
    df.SEShares = df.demFe  %>%
      left_join(df.demFETotal, by=c("region", "period", "entyFE")) %>%
      mutate(SEShare = demFE / demFETotal) %>%
      select(-demFE, -demFETotal)
    df.priceFuel <- df.priceFuel %>%
      left_join(df.SEShares, by=c("region", "period", "entySE", "entyFE")) %>%
      mutate(priceFuel = priceFuel * replace_na(SEShare, 0.)) %>% 
      group_by(region, period, entyFE) %>% 
      summarize(priceFuel = sum(priceFuel)) %>%
      ungroup

    #prices obtained from SE sector are not available before 2030, so we take pm_FEPrice for these
    df.priceFuel_before_2030 <- as.quitte(readGDX(gdx, "pm_FEPrice", restore_zeros = F)) %>%
      filter(sector == "indst", emiMkt == "ETS", value > 0., period %in% t, period<2030) %>%
      select(region, period, all_enty, value) %>%
      rename(entyFE = all_enty, priceFuel = value)

    df.priceFuel <- df.priceFuel %>%
        bind_rows(df.priceFuel_before_2030)

    df.priceFuel <- df.priceFuel[order(df.priceFuel$period, df.priceFuel$entyFE),]
  }
  else {
    print("Excluding CO2 price from fuel prices. Using SE prices only.")

    df.priceFuel <- as.quitte(readGDX(gdx, "pm_SEPrice", restore_zeros = F)) %>%
      filter(period %in% t) %>%
      select(region, period, all_enty, value) %>%
      rename(entySE = all_enty, priceSE = value)

    df.demFETotal = df.demFe  %>% 
      group_by( region, period, entyFE) %>% 
      summarize(demFETotal = sum(demFE)) %>%
      ungroup

    df.SEShares = df.demFe  %>%
      left_join(df.demFETotal, by=c("region", "period", "entyFE")) %>%
      mutate(SEShare = demFE / demFETotal) %>%
      select(-demFE, -demFETotal)

    df.priceFuel <- df.priceFuel %>%
      left_join(df.SEShares, by=c("region", "period", "entySE")) %>%
      filter(!is.na(entyFE))  #some SE prices have no corresponding FE demand for industry (seliqsyn, sehe, segasyn). remove them

    #add transmission and distribution costs
    df.priceFuel <- calc_td_costs(gdx, df.priceFuel)

    #### Subtract CO2 tax from fuel price (currently only needs ot be done for elec)
    df.priceFuel <- df.priceFuel %>%
      left_join(df.FeEmiCost, by=c("region", "period", "entyFE")) %>%
      mutate(priceFuel = priceFuel - ifelse(is.na(FeEmiCost), 0., FeEmiCost)) %>%
      select(-FeEmiCost)

    }
  ### calculate Fe demand for the different steel routes, and the corresponding FE cost per ton of steel (USD/?t)

  # specFeDem is given in TWa/Gt.
  df.specFeDem <- as.quitte(readGDX(gdx,name=c("pm_specFeDem"),format="first_found",restore_zeros = F)) %>% 
    filter(value > 0., period %in% t) %>%
    select(region, period, all_enty, all_te, opmoPrc, value) %>%
    rename(entyFE = all_enty, specFeDem = value)

  # prices are given in trUSD/TWa,
  # so cost fuel is in trUSD/Gt or USD/t
  df.costFuel <- df.specFeDem %>% 
    left_join(df.priceFuel, by = c("region", "period", "entyFE"))

  df.costFuel <- df.costFuel %>% 
    mutate(value = specFeDem * priceFuel) %>% 
    mutate(component = entyFE) %>% 
    select(-priceFuel, -specFeDem, -entyFE)

  
  return(df.costFuel)
}

```


```{R calculate material costs}

calc_material_costs <- function(gdx) {
  # calculate costs from DRI pellets, iron ore ..
  ###################################################
  # MATERIAL
  # calculates cost of material required
  # for DRIEAF: dri pellets, dri iron. If secondary EAF, additional scrap.
  # for BFBOF: iron ore, pig iron, BOF scrap (very very small)

  #define sets needed
  regi <- readGDX(gdx,"regi")

  #specMatDem is given in t/t
  specMatDem <- as.quitte(readGDX(gdx,name=c("p37_specMatDem"),format="first_found",restore_zeros = F)) %>% 
    filter(value > 0.) %>%
    select(mat, all_te, opmoPrc, value) %>%
    rename( specMatDem = value)

  priceMat <- as.quitte(readGDX(gdx,name=c("p37_priceMat"),format="first_found",restore_zeros = F)) %>% 
    filter(value > 0.) %>%
    select(all_enty, value) %>%
    rename( priceMat = value, mat = all_enty)

  #final costs are in USD/t or trUSD/Gt 
  df.costMat = specMatDem %>% 
    left_join(priceMat, by = "mat") %>% 
    mutate(value = specMatDem * priceMat) %>% 
    filter(value > 0.) %>%
    rename(component = mat) %>% 
    select(-specMatDem, -priceMat) %>%
    crossing(t, regi) %>% 
    rename(period = t, region = regi)
  return(df.costMat)
}
```

```{R calc CAPEX and OPEX}

calc_CAPEX_and_OPEX <- function(gdx){
  #### CALC CAPEX

  #in USD/t capacity
  df.CAPEX <- as.quitte(readGDX(gdx, "vm_costTeCapital", field = "l", restore_zeros = F)[,t,tePrcAll]) %>%
      select(region, period, all_te, value) %>%
      mutate(component = "CAPEX")

  #### CALC OPEX
  # requires capacity factor and O&M costs
  df.capFac <- as.quitte(readGDX(gdx, "vm_capFac", field="l", restore_zeros = F)[,t,]) %>%
      select(region, period, all_te, value) %>%
      filter(all_te %in% tePrcAll ) %>%
      rename(capFac = value)

  df.OMF <- as.quitte(readGDX(gdx, "pm_data", restore_zeros = F)[,,"omf"]) %>%
      select(region, all_te, value) %>%
      filter(all_te %in% tePrcAll, value > 0.) %>%
      # OMF is relative to CAPEX / capfac 
      full_join(df.CAPEX %>% 
                  left_join(df.capFac, by=c("region", "period", "all_te")) %>%
                  mutate(value = value / capFac) %>%  # conversion from MW/a to MWh/a
                  rename(CAPEX = value) %>%
                  select(region, period, all_te, CAPEX),
                by=c("region", "all_te")) %>%
      mutate(value = value * CAPEX ) %>% 
      select(-CAPEX)

  #empty df: no OMV defined for steel production (for now)
  df.OMV <- as.quitte(readGDX(gdx, "pm_data", restore_zeros = F)[,,"omv"]) %>%
      select(region, all_te, value) %>%
      filter(all_te %in% tePrcAll, value > 0.)

  df.OPEX <- bind_rows(df.OMF, df.OMV) %>% 
    group_by( region, period, all_te) %>% 
    summarize(value = sum(value)) %>%
    ungroup  %>%
    mutate(component = "OPEX") %>% 
    full_join(tePrc2opmoPrc, by="all_te")

  return(list(CAPEX = df.CAPEX, OPEX = df.OPEX))
}


```

```{R calc total costs}

calc_cumulative_costs <- function(df, start_year, end_year) {
  full_timesteps <- seq(start_year, end_year, by=5)

  df_expanded <- expand.grid(
    region = unique(df$region),
    period = full_timesteps,
    component = unique(df$component),
    scenario = unique(df$scenario)
  )

  full_df <- df_expanded %>%
    left_join(df, by = c("region", "period", "component", "scenario"))

  #test: raise error if more than one period has na value (for up to 2070, expect 1 na period, 2065)
  na_df <- full_df %>% filter(is.na(value))
  if (length(unique(na_df$period)) > 1) {
    print(unique(na_df$period))
    stop("There are more NA values than expected in the data frame.")
  }

  full_df <- full_df %>%
    group_by(region, component, scenario) %>%
    arrange(period) %>%
    # if NA (should only be for 2065) use lead value to fill time step that is not calculated
    mutate(value = ifelse(is.na(value), lead(value), value)) %>%
    #since the variables are defined such that 2070 = between 2067.5 and 2072.5, we multiply the value by 2.5 for the last year step
    # to get the cumulative value until end_year, not end_year + 2.5
    mutate(value_5_year = ifelse(period == end_year, value * 2.5, value * 5)) %>%
    mutate(cumulative_value = cumsum(value_5_year)) %>%
    ungroup() %>% 
    select(region, period, scenario, component, cumulative_value)

  return(full_df)
}

```

```{R combine costs}
calc_total_costs <- function(gdx, scenario_name, include_co2_price = TRUE, start_year = 2020, end_year = 2070) {
  #### COMBINE COSTS
  # calculate and combine df.costFuel, df.costMat, df.CAPEX, df.OPEX
  # they need to be multiplied either by the production (costs and OPEX) or the capacity additions (CAPEX)
  # all quantities below should be in Gt/a or Gt
  # all the costs are in USD/t, corresponding to trUSD/Gt

  # calculate df.costFuel, df.costMat, df.CAPEX, df.OPEX
  df.costFuel <- calc_energy_costs(gdx, include_co2_price = include_co2_price)
  df.costMat <- calc_material_costs(gdx)
  df.CAPEX_OPEX <- calc_CAPEX_and_OPEX(gdx)
  df.CAPEX <- df.CAPEX_OPEX$CAPEX
  df.OPEX <- df.CAPEX_OPEX$OPEX



  # get yearly production, Gt/a. outflowPrc (2005) is the avg production between 2002.5 and 2007.5
  df.outflowPrc <- as.quitte(readGDX(gdx, "vm_outflowPrc", field = "l", restore_zeros = F)[,t,]) %>%
    filter(all_te %in% tePrcAll) %>%
    select(region, period, all_te, value, opmoPrc) %>%
    rename(outflowPrc = value)

  #vm_delatCap are the annual capacity additions. vm_deltaCap 2005 = annual capacity additions between 2001 and 2005.
  df.deltacap <- as.quitte(readGDX(gdx, "vm_deltaCap", field = "l", restore_zeros = F)[,t,]) %>%
    filter(all_te %in% tePrcAll) %>%
    select(region, period, all_te, value) %>%
    rename(deltacap = value)

  # we have to match vm_deltacap with the standard REMIND variables, ie defining 2005 as 2002.5 -> 2007.5.
  # for this, we need to recalculate df.deltacap.
  # the additions in 2005 are now (3.5* vm_deltacap("2005") + 1.5 * vm_deltacap("2010"))/5 to get the yearly amount
  df.deltacap_new <- df.deltacap %>%
      group_by(region, all_te) %>%
      mutate(deltacap_new = (3.5 * deltacap +1.5*lead(deltacap))/5) %>%
      ungroup() %>%
      mutate(deltacap_new = ifelse(is.na(deltacap_new), deltacap, deltacap_new)) %>% #values for 2100 cant be calculated because there is no 2105 value
      select(-deltacap) %>%
      rename(deltacap = deltacap_new)

  #calc total CAPEX per year (trUSD)
  df.CAPEX_total <- df.CAPEX %>%
    left_join(df.deltacap_new, by=c("region", "period", "all_te")) %>%
    mutate(value = value * deltacap ) %>%
    select(-deltacap) %>%
    group_by(region, period) %>%
      summarise(value = sum(value)) %>%
      ungroup() %>%
      mutate(component = "CAPEX")

  #calc total OPEX, matcost, energy costs per year (trUSD)
  df.OPEX_total <- df.OPEX %>%
    left_join(df.outflowPrc, by=c("region", "period", "all_te", "opmoPrc")) %>%
    mutate(value = value * outflowPrc) %>%
    select(-outflowPrc) %>%
      group_by(region, period) %>%
          summarise(value = sum(value)) %>%
          ungroup() %>%
          mutate(component = "OPEX")

  df.costFuel_total <- df.costFuel %>%
    left_join(df.outflowPrc, by=c("region", "period", "all_te", "opmoPrc")) %>%
    mutate(value = value * outflowPrc) %>%
    select(-outflowPrc) %>%
      group_by(region, period) %>%
          summarise(value = sum(value)) %>%
          ungroup() %>%
          mutate(component = "Energy costs")

  df.costMat_total <- df.costMat %>%
      left_join(df.outflowPrc, by=c("region", "period", "all_te", "opmoPrc")) %>%
      mutate(value = value * outflowPrc) %>%
      select(-outflowPrc) %>%
      group_by(region, period) %>%
          summarise(value = sum(value)) %>%
          ungroup() %>%
          mutate(component = "Materials")

  #costs given in trUSD
  df.totalcosts <- df.CAPEX_total %>%
    bind_rows(df.OPEX_total) %>%
    bind_rows(df.costFuel_total) %>%
    bind_rows(df.costMat_total)

  #add the aggregate global costs
  df.totalglobalcosts <- df.totalcosts %>%
    group_by(period, component) %>%
    summarise(value = sum(value)) %>%
    ungroup() %>%
    mutate(region = "GLO")

  df.totalcosts <- df.totalcosts %>%
    bind_rows(df.totalglobalcosts) %>% 
    mutate(scenario = scenario_name)

  #calculate cumulative costs
  df.cumulativecosts <- calc_cumulative_costs(df.totalcosts, start_year = start_year, end_year = end_year)

  return(list(yearly = df.totalcosts, cumu = df.cumulativecosts))
}
```

```{R calc investments}

calc_total_investments <- function(gdx) {
  # calculate additional electrolyser investments required for the steel sector

    # only works for the short term (up to 2050-2055) as we do not account for lifetime of investments

  # calculate h2 demand from the steel sector
  # specFeDem is given in TWa/Gt.
  df.specFeDemH2 <- as.quitte(readGDX(gdx,name=c("pm_specFeDem"),format="first_found",restore_zeros = F)) %>% 
    filter(value > 0., period %in% t, all_enty == "feh2s") %>%
    select(region, period, all_enty, all_te, opmoPrc, value) %>%
    rename(entyFE = all_enty, specFeDem = value)


  df.specFeDemEl <- as.quitte(readGDX(gdx,name=c("pm_specFeDem"),format="first_found",restore_zeros = F)) %>% 
    filter(value > 0., period %in% t, all_enty == "feels") %>%
    filter(all_te %in% c("idr", "eaf")) %>%
    select(region, period, all_enty, all_te, opmoPrc, value) %>%
    rename(entyFE = all_enty, specFeDem = value)

  df.specFeDemFos <- as.quitte(readGDX(gdx,name=c("pm_specFeDem"),format="first_found",restore_zeros = F)) %>% 
    filter(value > 0., period %in% t, all_enty %in% c("fegas", "fesos")) %>%
    select(region, period, all_enty, all_te, opmoPrc, value) %>%
    rename(entyFE = all_enty, specFeDem = value)

  # get yearly production, Gt/a. outflowPrc (2005) is the avg production between 2002.5 and 2007.5
  df.outflowPrc <- as.quitte(readGDX(gdx, "vm_outflowPrc", field = "l", restore_zeros = F)[,t,]) %>%
    filter(all_te %in% tePrcAll) %>%
    select(region, period, all_te, value, opmoPrc) %>%
    rename(outflowPrc = value)

  ## CALC STEEL CAPEX

  # PART 1: DRI and EAF
  #for dri and primary EAF

  #get steel capacity factors
  df.capfac_steel <- as.quitte(readGDX(gdx, "vm_capFac", field = "l", restore_zeros = F)[,t,]) %>%
    filter(all_te %in% tePrc) %>%
    select(region, period, all_te, value) %>%
    rename(capFac = value)

  # calculate DRI-H2 CAPEX + EAF CAPEX for the capacity required for H2-DRI
  #in USD/t capacity
  df.CAPEX_steel <- as.quitte(readGDX(gdx, "vm_costTeCapital", field = "l", restore_zeros = F)[,t,tePrcAll]) %>%
      select(region, period, all_te, value) %>%
      filter(all_te %in% c("idr", "eaf", "bf", "bof", "bfcc")) %>%
      rename(capex = value)

  # get yearly production, Gt/a. outflowPrc (2005) is the avg production between 2002.5 and 2007.5
  df.outflowPrc_prdri <- df.outflowPrc %>%
    filter((all_te == "idr")|(all_te == "eaf")) 
    # %>%
    # summarise to calculate total volume of DRI iron produced (both ng and h2)
    # they must both be accounted for in the calculation
    # group_by(region, period, all_te) %>%
    # summarise(outflowPrc = sum(outflowPrc)) %>%
    # ungroup()


  df.Inv_steel <- df.outflowPrc_prdri %>%
    left_join(df.capfac_steel, by = c("region", "period", "all_te")) %>%
    mutate(steelcap = outflowPrc / capFac) %>%
    group_by(region, all_te, opmoPrc) %>%
    arrange(period) %>%
    mutate(steelexistingcap = steelcap) %>%
    # mostly necessary for US: fill in missing values when H2 is not used for some time steps
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap,2), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap,3), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap,4), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(is.na(steelexistingcap), 0, steelexistingcap)) %>%
    #calculate required electrolysis additions (disreguard years requiring less H2)
    mutate(deltacap = steelexistingcap - lag(steelexistingcap)) %>%
    mutate(deltacap = ifelse(is.na(deltacap), 0, deltacap)) %>%
    mutate(deltacap = ifelse(deltacap < 0, 0, deltacap)) %>%
    select(region, all_te, period, deltacap, opmoPrc) %>%
    ungroup() %>%
    # mutate(component = paste0("Steel CAPEX (", all_te, "-", opmoPrc, ")") ) %>%
    mutate(component = ifelse(all_te == "eaf"& opmoPrc == "sec", 
                              "Steel CAPEX (eaf secondary)",
                              "Steel CAPEX (dri-eaf)"
                              ) ) %>%
    left_join(df.CAPEX_steel, by = c("region","period", "all_te")) %>%
    mutate(value = deltacap * capex) %>%
    select(region, period, value, all_te, component) %>%
    group_by(region, period, component) %>%
    summarise(value = sum(value)) %>% 
    ungroup()

  #PART 2: BF, BOF and BF-CCS
  df.outflowPrc_prfossil <- df.outflowPrc %>%
    filter(all_te %in% c("bf", "bof", "bfcc")) %>%
    group_by(region, period, all_te) %>%
    summarise(outflowPrc = sum(outflowPrc)) %>%
    ungroup()

  df.Inv_steel_fossil <- df.outflowPrc_prfossil %>%
    left_join(df.capfac_steel, by = c("region", "period", "all_te")) %>%
    mutate(steelcap = outflowPrc / capFac) %>%
    group_by(region, all_te) %>%
    arrange(period) %>%
    mutate(steelexistingcap = steelcap) %>%
    # mostly necessary for US: fill in missing values when H2 is not used for some time steps
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap,2), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap,3), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(steelexistingcap == 0., lag(steelexistingcap,4), steelexistingcap)) %>%
    mutate(steelexistingcap = ifelse(is.na(steelexistingcap), 0, steelexistingcap)) %>%
    #calculate required electrolysis additions (disreguard years requiring less H2)
    mutate(deltacap = steelexistingcap - lag(steelexistingcap)) %>%
    # initialisation issue: for 2010 so doesn't matter much.
    mutate(deltacap = ifelse(is.na(deltacap), ifelse(steelexistingcap != 0, steelexistingcap, 0), deltacap)) %>%
    mutate(deltacap = ifelse(deltacap < 0, 0, deltacap)) %>%
    # select(region, all_te, period, deltacap) %>%
    ungroup() %>%
    #for now, report only bfcc. Could also compute bfcc-bof by taking the factor of bfcc/bf production
    mutate(component = ifelse(all_te == "bfcc",
                            "Steel CAPEX (bf-ccs)",
                            "Steel CAPEX (bf-bof)")) %>% 
    left_join(df.CAPEX_steel, by = c("region","period", "all_te")) %>%
    mutate(value = deltacap * capex) %>%
    select(region, period, value, all_te, component) %>%
    group_by(region, period, component) %>%
    summarise(value = sum(value)) %>% 
    ungroup()


  ##### NOW, H2 CAPEX: ELECTROLYSIS + ELECTRICTY FOR ELECTROLYSIS
  # calc H2 dem in TWa/a (avg demand between 2002.5 and 2007.5)
  df.FeDemH2 <- df.specFeDemH2 %>%
    left_join(df.outflowPrc, by=c("region", "period", "all_te", "opmoPrc")) %>%
    mutate(h2dem = specFeDem * outflowPrc) %>%
    filter(period <= 2055, period >= 2020) %>%
    select(region, period, h2dem, entyFE)

  # electrolyser capfac to calculate overall electrolysis capacity required
  df.elh2capfac <- as.quitte(readGDX(gdx, "vm_capFac", field = "l", restore_zeros = F)[,t,]) %>%
    filter(all_te == "elh2") %>%
    select(region, period, value) %>%
    rename(capFac = value)

  # eta, electrolyser efficiency
  # use to calculate electricity demand from H2 demand
  df.eta <- as.quitte(readGDX(gdx, "pm_eta_conv", restore_zeros = F)[,t,]) %>%
      filter(all_te == "elh2", value > 0.) %>%
      select(region, period, value) %>%
      rename(eta = value)

  df.elDem_elh2 <- df.FeDemH2 %>%
    left_join(df.eta, by=c("region", "period")) %>%
    mutate(eldem = h2dem / eta) %>%
    select(region, period, eldem)

  # FLH given in pm_dataren * pm_cf (but pm_cf is basically 1 everywhere. Except for some periods in China for whatever reason)
  df.capfac_el <- as.quitte(readGDX(gdx, "pm_dataren", restore_zeros = F)[,,,]) %>%
    select(region, value, char, rlf, all_te) %>%
    filter(char == "nur", all_te == "spv", rlf == 1) %>%
    rename(capfac = value)


  # PART1: ELECTROLYSIS CAPEX
  # merge dfs and calculate elh2 (capacity) required before calculating the required capacity additions
  df.totalH2dem <- df.FeDemH2 %>%
    left_join(df.elh2capfac, by=c("region", "period")) %>%
    mutate(elh2cap_required = h2dem / capFac) %>%
    group_by(region) %>%
    arrange(period) %>%
    mutate(elh2existingcap = elh2cap_required) %>%
    # mostly necessary for US: fill in missing values when H2 is not used for some time steps
    mutate(elh2existingcap = ifelse(elh2existingcap == 0., lag(elh2existingcap), elh2existingcap)) %>%
    mutate(elh2existingcap = ifelse(elh2existingcap == 0., lag(elh2existingcap,2), elh2existingcap)) %>%
    mutate(elh2existingcap = ifelse(elh2existingcap == 0., lag(elh2existingcap,3), elh2existingcap)) %>%
    mutate(elh2existingcap = ifelse(elh2existingcap == 0., lag(elh2existingcap,4), elh2existingcap)) %>%
    mutate(elh2existingcap = ifelse(is.na(elh2existingcap), 0, elh2existingcap)) %>%
    #calculate required electrolysis additions (disreguard years requiring less H2)
    mutate(deltacap = elh2existingcap - lag(elh2existingcap)) %>%
    mutate(deltacap = ifelse(is.na(deltacap), 0, deltacap)) %>%
    mutate(deltacap = ifelse(deltacap < 0, 0, deltacap)) %>%
    select(region, period, deltacap) %>%
    ungroup() %>% 
    mutate(all_te = "elh2",
          component = "Electrolysis CAPEX")

  # PART 2: ELECTRICITY CAPEX FOR ELECTROLYSIS
  # merge dfs and calculate spv (capacity) required for electrolysis
  # then, calculate the required capacity additions
  df.elDem_elh2 <- df.elDem_elh2 %>%
    left_join(df.capfac_el, by=c("region")) %>%
    mutate(cap_el = eldem / capfac) %>%
    select(region, period, cap_el) %>%
    group_by(region) %>%
    arrange(period) %>%
    mutate(cap_el_required = cap_el) %>%
    # mostly necessary for US: fill in missing values when H2 is not used for some time steps
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required,2), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required,3), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required,4), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(is.na(cap_el_required), 0, cap_el_required)) %>%
    #calculate required electrolysis additions (disreguard years requiring less H2)
    mutate(deltacap = cap_el_required - lag(cap_el_required)) %>%
    mutate(deltacap = ifelse(is.na(deltacap), 0, deltacap)) %>%
    mutate(deltacap = ifelse(deltacap < 0, 0, deltacap)) %>%
    ungroup() %>%
    select(region,period, deltacap) %>%
    mutate(all_te = "spv",
          component = "Electricity CAPEX (for electrolysis)")

  # get the CAPEX for elh2
  # in USD/(W/a) capacity?? So divided by 1000 relative to generisdatatech.
  # multiplied by TW => tr USD units
  df.CAPEX <- as.quitte(readGDX(gdx, "vm_costTeCapital", field = "l", restore_zeros = F)[,t,]) %>%
  # TODO: filter for spv as well
    filter((all_te == "elh2") | (all_te == "spv")) %>%
    select(region, period, all_te, value) %>%
    rename(capex = value)

  # combine electricity and hydrogen investment requirements
  # calculate total investment costs 
  # vm_cap should be in TW. so final cost unit here is in trUSD
  df.Inv_el_h2 <- df.elDem_elh2 %>% 
    bind_rows(df.totalH2dem) %>% 
    left_join(df.CAPEX, by=c("region", "period", "all_te")) %>%
    mutate(value = deltacap * capex) %>%
    select(region, period, value, component)

  #### NOW: OTHER ELEC DEMAND (EAF + IDR + SEC EAF)

  df.elDem1 <- df.specFeDemEl %>%
    left_join(df.outflowPrc, by = c("region", "period","all_te", "opmoPrc")) %>%
    mutate(dem = specFeDem * outflowPrc) %>%
    group_by(region, period, entyFE) %>%
    summarise(eldem = sum(dem))

  # merge dfs and calculate spv (capacity) required for electrolysis
  # then, calculate the required capacity additions
  df.elDem <- df.elDem1 %>%
    left_join(df.capfac_el, by=c("region")) %>%
    mutate(cap_el = eldem / capfac) %>%
    select(region, period, cap_el) %>%
    group_by(region) %>%
    arrange(period) %>%
    mutate(cap_el_required = cap_el) %>%
    # mostly necessary for US: fill in missing values when H2 is not used for some time steps
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required,2), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required,3), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(cap_el_required == 0., lag(cap_el_required,4), cap_el_required)) %>%
    mutate(cap_el_required = ifelse(is.na(cap_el_required), 0, cap_el_required)) %>%
    #calculate required electrolysis additions (disreguard years requiring less H2)
    mutate(deltacap = cap_el_required - lag(cap_el_required)) %>%
    mutate(deltacap = ifelse(is.na(deltacap), 0, deltacap)) %>%
    mutate(deltacap = ifelse(deltacap < 0, 0, deltacap)) %>%
    ungroup() %>%
    select(region,period, deltacap) %>%
    mutate(all_te = "spv",
          component = "Electricity CAPEX (other)")

  df.Inv_el <- df.elDem %>% 
    left_join(df.CAPEX, by=c("region", "period", "all_te")) %>%
    mutate(value = deltacap * capex) %>%
    select(region, period, value, component)

  ### CALC FOSSIL OPEX FEGAS AND FESOS

  df.FosDem <- df.specFeDemFos %>%
    left_join(df.outflowPrc, by = c("region", "period","all_te", "opmoPrc")) %>%
    mutate(dem = specFeDem * outflowPrc) %>%
    group_by(region, period, entyFE) %>%
    summarise(fosdem = sum(dem))

  # calc fuel prices (including CO2 prices)
  df.priceFuel <- as.quitte(readGDX(gdx, "p_FEPrice_by_SE_Sector_EmiMkt", restore_zeros = F)) %>%
    filter(sector == "indst", emiMkt == "ETS", value > 0., period %in% t) %>%
    select(region, period, entySe, all_enty, value) %>%
    rename(entySE = entySe, entyFE = all_enty, priceFuel = value)

  df.demFe <- as.quitte(readGDX(gdx, "vm_demFeSector_afterTax", field = "l", restore_zeros = F)[,t,]) %>%
    # dimensions: vm_demFeSector_afterTax(ttot,regi,entySE,entyFE,"indst",emiMkt)
    filter(all_enty1 %in% entyFE, emi_sectors == "indst", all_emiMkt == "ETS", value > 0.) %>%
    select(period, region, all_enty, all_enty1, value) %>%
    rename(demFE = value, entySE = all_enty, entyFE = all_enty1)
  df.demFETotal = df.demFe  %>% 
    group_by( region, period, entyFE) %>% 
    summarize(demFETotal = sum(demFE)) %>%
    ungroup
  df.SEShares = df.demFe  %>%
    left_join(df.demFETotal, by=c("region", "period", "entyFE")) %>%
    mutate(SEShare = demFE / demFETotal) %>%
    select(-demFE, -demFETotal)

  #comment out to inlude CO2 pricing
  #to use SE prices (no CO2 pricing): 
  df.priceFuel <- as.quitte(readGDX(gdx, "pm_SEPrice", restore_zeros = F)) %>%
      filter(period %in% t) %>%
      select(region, period, all_enty, value) %>%
      rename(entySE = all_enty, priceSE = value)

  df.demFETotal = df.demFe  %>% 
      group_by( region, period, entyFE) %>% 
      summarize(demFETotal = sum(demFE)) %>%
      ungroup

  df.SEShares = df.demFe  %>%
    left_join(df.demFETotal, by=c("region", "period", "entyFE")) %>%
    mutate(SEShare = demFE / demFETotal) %>%
    select(-demFE, -demFETotal)

  df.priceFuel <- df.priceFuel %>%
    left_join(df.SEShares, by=c("region", "period", "entySE")) %>%
    select(-SEShare) %>%
    filter(!is.na(entyFE)) %>%
    rename(priceFuel = priceSE)

  ## end of no CO2 pricing calculation

  df.priceFuel <- df.priceFuel %>%
    left_join(df.SEShares, by=c("region", "period", "entySE", "entyFE")) %>%
    mutate(priceFuel = priceFuel * replace_na(SEShare, 0.)) %>% 
    group_by(region, period, entyFE) %>% 
    summarize(priceFuel = sum(priceFuel)) %>%
    ungroup()
  

  #prices obtained from SE sector are not available before 2030, so we take pm_FEPrice for these
  df.priceFuel_before_2030 <- as.quitte(readGDX(gdx, "pm_FEPrice", restore_zeros = F)) %>%
    filter(sector == "indst", emiMkt == "ETS", value > 0., period %in% t, period<2030) %>%
    select(region, period, all_enty, value) %>%
    rename(entyFE = all_enty, priceFuel2 = value)

  df.FosDem <- df.FosDem %>%
    left_join(df.priceFuel, by=c("region", "period", "entyFE")) %>%
    left_join(df.priceFuel_before_2030, by=c("region", "period", "entyFE")) 
  
  df.FosDem <- df.FosDem %>%
    #if no weighted priceFuel is available, use the priceFuel2 (pm_FEprice)
    mutate(priceFuel = ifelse(is.na(priceFuel), priceFuel2, priceFuel)) %>%
    select(-priceFuel2) %>%
    mutate(value = fosdem * priceFuel *5 ) %>% #*5 because the demand is in TWa/a, and the investments are given over the whole time step (5y)
    # NB. all investments are then translated to USD/yr at the end of the function
    select(region, period, value, entyFE) %>%
    rename(component = entyFE)

  ### BRING EVERYTHING TOGETHER
  df.total_Inv <- df.Inv_steel %>%
    bind_rows(df.Inv_steel_fossil) %>%
    bind_rows(df.Inv_el_h2) %>%
    bind_rows(df.Inv_el) %>%
    bind_rows(df.FosDem) %>%
    mutate(value = value/5) #make value yearly cost. 
    #Only works up to 2060, afterwards model takes 10 yr time steps
    #but this estimation is also only valid up to 2050/2055
  return(df.total_Inv)
}


```


```{R calc cumu investment costs}
calc_cumu_investment_costs <- function(df, discount = 0.05){
  # annualize the costs
  df_discounted <- df %>%
    group_by(region, scenario, component) %>%
    complete(period = full_seq(period, 1)) %>%  # Fill every year
    arrange(region, scenario, component, period) %>%
    mutate(value1 = value) %>%
    fill(value1, .direction = "down") %>%
    ungroup() %>%
    select(-value) %>%
    # use correct time periods. Earliest time period is 2028.
    mutate(period = period - 2) 

  min_period = min(df_discounted$period, na.rm = TRUE)

  df_discounted <- df_discounted  %>%
    # multiply by discount factor and take cumulative sum
    arrange(region, scenario, component, period) %>%
    mutate(discounted_cost = value1 / ((1 + discount) ^ (period - min_period))) %>%
    group_by(region, scenario, component) %>%
    # summarise(total_cost_lockin = sum(discounted_cost, na.rm = TRUE)) %>%
    mutate(cumulative_value = cumsum(discounted_cost)) %>%
    ungroup()
}

```
```{r load gdx}
gdx <- "inputdata/gdx/GreenPolicy-PkBudg650.gdx"
```

```{R load sets}
#define sets required (they are the same across all gdx files)
tePrc <- readGDX(gdx,"tePrc")
tePrcAll <- tePrc

tePrc2opmoPrc <- as.data.frame(readGDX(gdx,"tePrc2opmoPrc")) %>% 
  rename(all_te = tePrc)

entyFE <- as.vector(readGDX(gdx, name="entyFE"))

t <- readGDX(gdx,"ttot")
t <- as.numeric(t[t >= 2010 & t <= 2100])
```

```{R calculate investment costs}

greenpol <- "inputdata/gdx/GreenPolicy_noReliningForSomeRegions-PkBudg820.gdx"
base <- "inputdata/gdx/PolicyExtended-PkBudg820.gdx"
npi <- "inputdata/gdx/PolicyExtended-NPi.gdx"


region_to_plot <- "IND"

# #calculate costs
df.totalcosts1 <- calc_total_investments(greenpol) %>%
  filter(region == region_to_plot) %>%
  mutate(scenario = "Fast Transition")

df.totalcosts2 <- calc_total_investments(base) %>%
  filter(region == region_to_plot) %>%
  mutate(scenario = "Extended lock-in")

df.totalcosts3 <- calc_total_investments(npi) %>%
  filter(region == region_to_plot) %>%
  mutate(scenario = "NPi")



```

```{R tests}
df.totalcosts <- df.totalcosts1 %>%
  bind_rows(df.totalcosts2) %>%
  bind_rows(df.totalcosts3) %>%
  filter(period >= 2030, period <= 2055)


plot_df <- df.totalcosts %>%
  mutate(region = factor(region, levels = plotted_regions, labels = region_names$region_name)) %>%
  mutate(period = as.numeric(period)) %>%
  mutate(value = value * 1000) #convert to billion USD 

plot_df_cumu_invest <- calc_cumu_investment_costs(plot_df, discount = 0.05)
# print(df.totalcosts_plot %>% filter(region == "IND"), n=Inf)
```

```{R plot costs}

component_order <- c("fesos", "fegas", "Electricity CAPEX (other)","Electricity CAPEX (for electrolysis)", "Electrolysis CAPEX", "Steel CAPEX (dri-eaf)","Steel CAPEX (eaf secondary)", "Steel CAPEX (bf-ccs)", "Steel CAPEX (bf-bof)")

scen_order <- c( "NPi", "Extended lock-in", "Fast Transition")
# scen_order <- c( "NPi", "Green policy")

plot_df <- plot_df %>%
  mutate(
    period = as.integer(period),
    component = factor(component, levels = component_order), 
    scenario = factor(scenario, levels = scen_order)
  )

component_colors <- c(
  "Electricity CAPEX (other)" = "#fad231",
  "Electricity CAPEX (for electrolysis)" = "#da9e06",
  "Electrolysis CAPEX" = "#4fecdc",
  "Steel CAPEX (dri-eaf)" = "#33eea3",
  "Steel CAPEX (eaf secondary)" = "#1edf3e", 
  "Steel CAPEX (bf-bof)" = "#323232",
  "Steel CAPEX (bf-ccs)" = "#747373",
  "fegas" = "#0d4e8f7b", 
  "fesos" = "#7b3e0253"
)

plot_df <- plot_df %>%
  mutate(
    period = as.integer(period),
    component = factor(component, levels = component_order), 
    scenario = factor(scenario, levels = scen_order)
  ) %>%
  filter(!component %in% c("fesos", "fegas")) #remove fesos and fegas

total_cost_df <- plot_df %>%
  group_by(region,period, scenario) %>%
  summarise(value = sum(value)) %>%
  ungroup()

# Area plot
region_plot <- ggplot() +
  geom_bar(data = plot_df,
          aes(x = period, y = value, fill = factor(component)),
          position = "stack", 
          stat="identity", 
          width=3) +
  scale_fill_manual(values = component_colors) +
  facet_wrap(~ scenario, nrow = 3) +
  labs(
    title = "Investment costs for India, for a `NPi`, `Extended lock-in` and `Fast\ntransition` scenario (820 PkBudget)",
    x = "Year",
    y = "Investment costs\n(Bill. USD) per year",
    fill = "Component"
  ) +
  guides(fill=guide_legend(nrow=5)) +
  theme_bw(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  ) 
region_plot

#save
# ggsave("figs_temp/investment_costs_820_IND.png", plot = region_plot, width = 8, height = 13, dpi = 300)
```

```{R plot costs CUMU}

component_order <- c("Fossil gas and biogas\n(excluding hydrogen)","Coal and biomass solids", "Electricity CAPEX (other)","Electricity CAPEX (for electrolysis)", "Electrolysis CAPEX", "Steel CAPEX (eaf secondary)","Steel CAPEX (dri-eaf)", "Steel CAPEX (bf-ccs)", "Steel CAPEX (bf-bof)")

scen_order <- c( "NPi", "Extended lock-in", "Fast Transition")
# scen_order <- c( "NPi", "Green policy")

final_year = 2040

component_colors <- c(
  "Electricity CAPEX (other)" = "#fad231",
  "Electricity CAPEX (for electrolysis)" = "#da9e06",
  "Electrolysis CAPEX" = "#4fecdc",
  "Steel CAPEX (eaf secondary)" = "#1edf3e",
  "Steel CAPEX (dri-eaf)" = "#33eea3", 
  "Steel CAPEX (bf-bof)" = "#323232",
  "Steel CAPEX (bf-ccs)" = "#747373",
  "Fossil gas and biogas\n(excluding hydrogen)" = "#0d4e8f7b", 
  "Coal and biomass solids" = "#7b3e0253"
)

plot_df_all <- plot_df_cumu_invest %>%
  mutate(
    period = as.integer(period),
    scenario = factor(scenario, levels = scen_order)
  ) %>%
  filter(period <= final_year) %>%
  group_by(region, scenario, component) %>%
  summarise(mean = max(cumulative_value) / (max(period) - min(period))) %>%
  ungroup()

plot_df <- plot_df_all %>%
  mutate(type = ifelse(component %in% c("fesos", "fegas"), "Additional OPEX\n(without CO2 pricing)", "Investment costs")) %>%
  mutate(component = gsub("fesos", "Coal and biomass solids", component)) %>%
  mutate(component = gsub("fegas", "Fossil gas and biogas\n(excluding hydrogen)", component)) %>%
  mutate(component = factor(component, levels = component_order)) 
  

plot_df$type <- factor(plot_df$type, levels = c("Investment costs", "Additional OPEX\n(without CO2 pricing)")) 

total_df <- plot_df %>%
  group_by(region, scenario) %>%
  summarise(total = sum(mean, na.rm = TRUE)) %>%
  ungroup() %>%
  select(region, scenario, total)

# Area plot
region_plot <- ggplot() +
  geom_bar(data = plot_df,
          aes(x = scenario, y = mean, fill = factor(component)),
          position = "stack", 
          stat="identity") +
  scale_fill_manual(values = component_colors) +
    # geom_text(aes(scenario, total+6, label = round(total,1), fill = NULL), data = total_df) +
  facet_wrap(~ type, scales = "free" ) +
  labs(
    title = "Average investment costs and operational expenditure for the steel sector in India,\nbetween today and 2040",
    x = "Year",
    y = "Investment costs\n(Bill. USD) per year",
    fill = "Component"
  ) +
  guides(fill=guide_legend(nrow=3)) +
  theme_bw(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  ) 
region_plot

#save
# ggsave("figs_temp/investment_costs_avg_IND.png", plot = region_plot, width = 12, height = 8, dpi = 300)
```


```{R calculate investment costs}

base <- "inputdata/gdx/PolicyExtended-PkBudg820.gdx"
norelining <- "inputdata/gdx/GreenPolicy_noReliningForSomeRegions-PkBudg820.gdx"
npi <- "inputdata/gdx/PolicyExtended-NPi.gdx"


#calculate costs
df.totalcosts1 <- calc_total_investments(base) %>%
  mutate(scenario = "Extended lock-in")

df.totalcosts2 <- calc_total_investments(norelining) %>%
  mutate(scenario = "Fast transition")

df.totalcosts3 <- calc_total_investments(npi) %>%
  mutate(scenario = "NPi")
```

```{R tests}
df.totalcosts <- df.totalcosts1 %>%
  bind_rows(df.totalcosts2) %>%
  bind_rows(df.totalcosts3) %>%
  filter(period >= 2030, period <= 2050) %>%
  group_by(period, scenario, component) %>%
  # group_by(period, scenario) %>%
  summarise(value = sum(value)) %>%
  ungroup() %>%
  mutate(region = "Global")


plot_df <- df.totalcosts %>%
  # mutate(region = factor(region, levels = plotted_regions)) %>%
  mutate(period = as.numeric(period)) %>%
  mutate(value = value * 1000) #convert to billion USD 


# print(df.totalcosts_plot %>% filter(region == "IND"), n=Inf)
```

```{R plot costs}

component_order <- c("fesos", "fegas", "Electricity CAPEX (other)","Electricity CAPEX (for electrolysis)", "Electrolysis CAPEX", "Steel CAPEX (dri-eaf)","Steel CAPEX (eaf secondary)", "Steel CAPEX (bf-ccs)", "Steel CAPEX (bf-bof)")

scen_order <- c( "NPi", "Extended lock-in", "Fast transition")
# scen_order <- c( "NPi", "Green policy")

plot_df <- plot_df %>%
  mutate(
    period = as.integer(period),
    component = factor(component, levels = component_order), 
    scenario = factor(scenario, levels = scen_order)
  )

component_colors <- c(
  "Electricity CAPEX (other)" = "#fad231",
  "Electricity CAPEX (for electrolysis)" = "#da9e06",
  "Electrolysis CAPEX" = "#4fecdc",
  "Steel CAPEX (dri-eaf)" = "#33eea3",
  "Steel CAPEX (eaf secondary)" = "#1edf3e", 
  "Steel CAPEX (bf-bof)" = "#323232",
  "Steel CAPEX (bf-ccs)" = "#747373",
  "fegas" = "#0d4e8f7b", 
  "fesos" = "#7b3e0253"
)

plot_df <- plot_df %>%
  mutate(
    period = as.integer(period),
    component = factor(component, levels = component_order), 
    scenario = factor(scenario, levels = scen_order)
  ) %>%
  # # remove fesos and fegas
  filter(!component %in% c("fesos", "fegas"))

# Area plot
region_plot <- ggplot() +
  geom_bar(data = plot_df,
          aes(x = period, y = value, fill = factor(component)),
          position = "stack", 
          stat="identity", 
          width=3) +
  scale_fill_manual(values = component_colors) +
  facet_wrap(~ scenario, nrow = 3) +
  labs(
    title = "Investment costs for a `NPi`, `Fast Transition` and `Extended lock-in`\nscenario (820 PkBudget)",
    x = "Year",
    y = "Investment costs\n(Bill. USD) per year",
    fill = "Component"
  ) +
  guides(fill=guide_legend(nrow=3)) +
  theme_bw(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  ) 
region_plot

#save
# ggsave("figs_temp/investment_costs_820_global.png", plot = region_plot, width = 8, height = 11, dpi = 300)
```


```{R calculate investment costs per region}

norelining <- "inputdata/gdx/PolicyExtended_noRelining-PkBudg820.gdx"
# norelining <- "inputdata/gdx/GreenPolicy-PkBudg820.gdx"

df.totalcosts1 <- calc_total_investments(norelining) %>%
  mutate(scenario = "Fast transition")


plot_df <- df.totalcosts1 %>%
  filter(period >= 2030, period <= 2050) %>%
  # mutate(region = factor(region, levels = plotted_regions)) %>%
  mutate(period = as.numeric(period)) %>%
  mutate(value = value * 1000) #convert to billion USD 

```

```{R plot costs}

component_order <- c("fesos", "fegas", "Electricity CAPEX (other)","Electricity CAPEX (for electrolysis)", "Electrolysis CAPEX", "Steel CAPEX (dri-eaf)","Steel CAPEX (eaf secondary)", "Steel CAPEX (bf-ccs)", "Steel CAPEX (bf-bof)")

scen_order <- c( "NPi", "Extended lock-in", "Fast transition")
# scen_order <- c( "NPi", "Green policy")

plot_df <- plot_df %>%
  mutate(
    period = as.integer(period),
    component = factor(component, levels = component_order), 
    scenario = factor(scenario, levels = scen_order)
  )

component_colors <- c(
  "Electricity CAPEX (other)" = "#fad231",
  "Electricity CAPEX (for electrolysis)" = "#da9e06",
  "Electrolysis CAPEX" = "#4fecdc",
  "Steel CAPEX (dri-eaf)" = "#33eea3",
  "Steel CAPEX (eaf secondary)" = "#1edf3e", 
  "Steel CAPEX (bf-bof)" = "#323232",
  "Steel CAPEX (bf-ccs)" = "#747373",
  "fegas" = "#0d4e8f7b", 
  "fesos" = "#7b3e0253"
)

plot_df <- plot_df %>%
  mutate(
    period = as.integer(period),
    component = factor(component, levels = component_order), 
    scenario = factor(scenario, levels = scen_order)
  ) %>%
  # # remove fesos and fegas
  filter(!component %in% c("fesos", "fegas"))

# Area plot
region_plot <- ggplot() +
  geom_bar(data = plot_df,
          aes(x = period, y = value, fill = factor(component)),
          position = "stack", 
          stat="identity", 
          width=3) +
  scale_fill_manual(values = component_colors) +
  facet_wrap(~ region, nrow = 3) +
  labs(
    title = "Investment costs for a `NPi`, `Fast Transition` and `Extended lock-in`\nscenario (820 PkBudget)",
    x = "Year",
    y = "Investment costs\n(Bill. USD)",
    fill = "Component"
  ) +
  guides(fill=guide_legend(nrow=2)) +
  theme_bw(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    strip.text = element_text(face = "bold"),
    legend.position = "bottom"
  ) 
region_plot

#save
ggsave("figs_temp/investment_costs_820allregions.png", plot = region_plot, width = 8, height = 11, dpi = 300)
```


