 ---
title: "BOF Steel-making Capacity Plot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("ggplot2")

library(tidyverse)
library(ggplot2)
library(grid)
library(quitte)
# library(ggpattern)
require(gridExtra)

```

```{r readdata}
raw_data <- read.csv("inputdata/gspt/global_BOFcap.csv")

raw_age_data <- read.csv("inputdata/gspt/age_distribution.csv")

raw_age_data_region <- read.csv("inputdata/gspt/age_distribution_regions.csv")

df_production <- read.csv("inputdata/gspt/production.csv")

```

```{r clean data}
clean_column_names <- function(name) {
  name <- gsub("\\.+", "_", name)
  name <- sub("_$", "", name)
}

### CLEAN UP CAPACITY DATA

data <- raw_data %>% 
  rename_all(clean_column_names) %>%
  select(-Region, -X5year_BOF_capacity_additions)

# Calculate Total net existing bof capacity: historic (old) cap additions- retirement of historic plants
# additional "Total_net_BOF_capacity_no_retirement_date" is capacity for which no dates are known. We simulate a linear decrease in net capacity instead.
data <- data %>%
  mutate(Total_retired_BOF_capacity_old = Total_retired_BOF_capacity - Total_retired_BOF_capacity_new_projects) %>%
  mutate(Total_BOF_capacity_additions_old = Total_BOF_capacity_additions - Total_BOF_capacity_additions_new_projects ) %>%
  mutate(Total_net_BOF_capacity_no_retirement_date = Total_BOF_capacity_additions_no_retirement_date - Total_retired_BOF_capacity_no_retirement_date) %>%
  mutate(Total_net_existing_BOF_capacity = Total_BOF_capacity_additions_old - Total_retired_BOF_capacity_old + Total_net_BOF_capacity_no_retirement_date )

# Get net BOF capacity additions (the ones that are operating). Split it into under construction or announcement subsets
data <- data %>%
  mutate(New_BOF_capacity_additions_still_operating = Total_BOF_capacity_additions_new_projects - Total_retired_BOF_capacity_new_projects) %>%
  mutate(New_BOF_capacity_additions_still_operating_under_construction = New_BOF_capacity_additions_still_operating - Total_net_BOF_capacity_additions_new_projects_announced_only) %>%
  rename(New_BOF_capacity_additions_still_operating_announcements = Total_net_BOF_capacity_additions_new_projects_announced_only)
  

# net BOF capacity additions (for new plants) if plants have one relining, or 2 relinings (lifetime of 2x relining or 3x relining)
# simply a complement to derive the fraction of these new plants that are under construction
data <- data %>%
  mutate(Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction = Total_net_BOF_capacity_additions_new_projects_2_relining - Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only) %>%
  mutate(Total_net_BOF_capacity_additions_new_projects_1_relining_under_construction = Total_net_BOF_capacity_additions_new_projects_1_relining - Total_net_BOF_capacity_additions_new_projects_1_relining_announced_only)


data_long <- data %>%
    pivot_longer(cols = -index, names_to = "Category", values_to = "Capacity")

data_NetBOFcap <- data %>%
    select("Remaining_BOF_capacity", "index") %>%
    pivot_longer(cols = -index, names_to = "Category", values_to = "Capacity")

#convert to Mtpa (/ 1000)
data_NetBOFcap$Capacity <- data_NetBOFcap$Capacity / 1000
data_long$Capacity <- data_long$Capacity / 1000

colnames(data)

### CLEAN UP AGE DATA

age_data <- raw_age_data %>%
  rename_all(clean_column_names) %>%
  mutate(Total_BOF_capacity = Total_BOF_capacity / 1000)

age_data_region <- raw_age_data_region %>%
  rename_all(clean_column_names) %>%
  mutate(Total_BOF_capacity = Total_BOF_capacity / 1000)
```


```{r plot}

data_long_filtered <- data_long %>%
  filter(Category %in% c("Total_net_existing_BOF_capacity",
          "Total_retired_BOF_capacity_new_projects",
          "Total_retired_BOF_capacity_custom_calculated_retirement_date",
          "New_BOF_capacity_additions_still_operating_under_construction",
          "New_BOF_capacity_additions_still_operating_announcements",
          "index"))


data_long_filtered$Category <- factor(data_long_filtered$Category, 
                            levels = c("Total_retired_BOF_capacity_new_projects",
                              "Total_retired_BOF_capacity_custom_calculated_retirement_date",
                              "New_BOF_capacity_additions_still_operating_under_construction",
                              "New_BOF_capacity_additions_still_operating_announcements",
                              "Total_net_existing_BOF_capacity"))


p <- ggplot(data_long_filtered, aes(x = factor(index), y = Capacity, fill = Category)) +
  geom_bar(stat = "identity", data = data_long_filtered) +
  scale_fill_manual(values = c("Total_retired_BOF_capacity_new_projects" = "pink",
                              "New_BOF_capacity_additions_still_operating_under_construction" = "#e41c7d",
                              "New_BOF_capacity_additions_still_operating_announcements" = "#b11d36",
                              "Total_retired_BOF_capacity_custom_calculated_retirement_date" = "grey",
                              "Total_net_existing_BOF_capacity" = "#454444"),
                    labels = c("Total_retired_BOF_capacity_new_projects" = "Fraction of new BF-BOFs\nrequiring retirement or reinvestment",
                              "New_BOF_capacity_additions_still_operating_under_construction" = "New BF-BOF project (under construction)",
                              "New_BOF_capacity_additions_still_operating_announcements" = "New BF-BOF project (announced)",
                              "Total_retired_BOF_capacity_custom_calculated_retirement_date" = "Fraction of operating BF-BOF\nrequiring retirement or reinvestment",
                              "Total_net_existing_BOF_capacity" = "Operating BF-BOF capacity"))+
  labs(x = "Time period", y = "Global BF-BOF steel-making capacity (Mtpa)", fill = "Bar Legend", color = "Line Legend") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

p + geom_line(data = data_NetBOFcap, aes(x = factor(index), y = Capacity, group = Category, color = "Remaining_BOF_capacity"), linewidth = 1.5) +
  scale_color_manual(values = c("Remaining_BOF_capacity" = "black"),
                     labels = c("Remaining_BOF_capacity" = "Net operating BF-BOF capacity")) +
  scale_x_discrete(breaks = seq(2000, 2050, by = 5)) +
  theme(legend.position = "right")

#ggsave("figs/BOF_capacity_plot.png", width = 10, height = 6, dpi = 300)
```

```{r plot2 capacity}
x_breaks <- seq(2000, 2080, by = 5)
data_long_filtered <- data_long %>%
  filter(Category %in% c(
          "Total_net_existing_BOF_capacity",
          "Additional_net_BOF_capacity_operating_2_relining",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only",
          #"New_BOF_capacity_additions_still_operating_under_construction",
          #"New_BOF_capacity_additions_still_operating_announcements",
          "index"))


data_long_filtered$Category <- factor(data_long_filtered$Category, 
                            levels = c(
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction",
                              "Additional_net_BOF_capacity_operating_2_relining",
                              "Total_net_existing_BOF_capacity"))

#p <-
ggplot(data_long_filtered, aes(x = factor(index), y = Capacity, fill = Category)) +
  geom_bar(stat = "identity", data = data_long_filtered) +
  scale_fill_manual(values = c(
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction" = "#e41c7d",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only" = "#b11d36",
                              "Additional_net_BOF_capacity_operating_2_relining" = "grey",
                              "Total_net_existing_BOF_capacity" = "#454444"
                              ),
                    labels = c("Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction" = "New BF-BOF project (under construction)",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only" = "New BF-BOF project (announced)",
                              "Additional_net_BOF_capacity_operating_2_relining" = "Additional capacity remaining from operating projects\nif two BF relinings are carried out",
                              "Total_net_existing_BOF_capacity" = "Operating BF-BOF capacity"))+
  labs(x = "Time period", y = "Global BF-BOF steel-making capacity (Mtpa)", fill = "Bar Legend", color = "Line Legend") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_x_discrete(breaks = x_breaks)

# p + geom_line(data = data_NetBOFcap, aes(x = factor(index), y = Capacity, group = Category, color = "Remaining_BOF_capacity"), linewidth = 1.5) +
#   scale_color_manual(values = c("Remaining_BOF_capacity" = "black"),
#                      labels = c("Remaining_BOF_capacity" = "Net operating BF-BOF capacity")) +
#   scale_x_discrete(breaks = seq(2000, 2050, by = 5)) +
#   theme(legend.position = "right")

# ggsave("figs/BOF_capacity_plot_w2relining.png", width = 10, height = 6, dpi = 300)
```

```{r calc emissions}

data_long_filtered_em <- data_long %>%
  filter(Category %in% c(
          "Total_net_existing_BOF_capacity",
          "Additional_net_BOF_capacity_operating_1_relining",
          "Total_net_BOF_capacity_additions_new_projects_1_relining_announced_only",
          "Total_net_BOF_capacity_additions_new_projects_1_relining_under_construction",
          "Additional_cumulative_capacity_to_meet_gov_target",
          "index")) %>%
  filter(index >= 2020 & index <2071) %>%
  # mutate(Emissions = Capacity * 0.8 * 2.3) %>% #0.8 capacity factor, 2.3 tCO2/t steel. Unit is MtCO2/yr
  mutate(Emissions = ifelse(grepl("new_projects", Category), Capacity * 0.8 * 2, Capacity * 0.8 * 2.3)) #new additions are BAT = 2 tCO2/t steel

#take wide format to calculate cumulative caps
data_wide_em <- data_long_filtered_em %>%
  select(-Capacity) %>%
  filter(index >= 2025 & index <2071) %>%
  pivot_wider(names_from = Category, values_from = Emissions)

#clean df
data_wide_em[is.na(data_wide_em)] <- 0

#calculate cumulative emissions
data_wide_em_cumu <- data_wide_em %>%
  mutate(Cumu_oldBOF = cumsum(Total_net_existing_BOF_capacity)) %>%
  mutate(Cumu_oldBOF_1relining = cumsum(Total_net_existing_BOF_capacity + 
                                     Additional_net_BOF_capacity_operating_1_relining)) %>%
  mutate(Cumu_oldBOF_andnew = cumsum(Total_net_existing_BOF_capacity +
                                              Additional_net_BOF_capacity_operating_1_relining +
                                              Total_net_BOF_capacity_additions_new_projects_1_relining_announced_only +
                                              Total_net_BOF_capacity_additions_new_projects_1_relining_under_construction)) %>%
  mutate(Cumu_oldBOF_new_govtargets = cumsum(Total_net_existing_BOF_capacity +
                                              Additional_net_BOF_capacity_operating_1_relining +
                                              Total_net_BOF_capacity_additions_new_projects_1_relining_announced_only +
                                              Total_net_BOF_capacity_additions_new_projects_1_relining_under_construction +
                                              Additional_cumulative_capacity_to_meet_gov_target)) %>%
  select(index, Cumu_oldBOF,Cumu_oldBOF_1relining,Cumu_oldBOF_andnew, Cumu_oldBOF_new_govtargets)

# annoyingly, this needs to be in long format to work
data_long_em_cumu <- data_wide_em_cumu %>%
  pivot_longer(cols = -index, names_to = "Category", values_to = "Emissions")

data_long_em_cumu$Category <- factor(data_long_em_cumu$Category, 
                            levels = c(
                              "Cumu_oldBOF_new_govtargets",
                              "Cumu_oldBOF_andnew",
                              "Cumu_oldBOF_1relining",
                              "Cumu_oldBOF"))



```

```{r plot emissions}
x_breaks <- seq(2020, 2075, by = 5)

data_long_filtered_em$Category <- factor(data_long_filtered_em$Category, 
                            levels = c(
                              "Additional_cumulative_capacity_to_meet_gov_target",
                              "Total_net_BOF_capacity_additions_new_projects_1_relining_announced_only",
                              "Total_net_BOF_capacity_additions_new_projects_1_relining_under_construction",  
                              "Additional_net_BOF_capacity_operating_1_relining",
                              "Total_net_existing_BOF_capacity"))

p <- ggplot(data_long_filtered_em, aes(x = factor(index), y = Emissions, fill = Category)) +
  geom_bar(stat = "identity", data = data_long_filtered_em) +
  scale_fill_manual(values = c(
                              "Additional_cumulative_capacity_to_meet_gov_target" = "#8420f0",
                              "Total_net_BOF_capacity_additions_new_projects_1_relining_under_construction" = "#e41c7d",
                              "Total_net_BOF_capacity_additions_new_projects_1_relining_announced_only" = "#b11d36",
                              "Additional_net_BOF_capacity_operating_1_relining" = "grey",
                              "Total_net_existing_BOF_capacity" = "#454444"
                              ),
                    labels = c(
                              "Additional_cumulative_capacity_to_meet_gov_target" = "Additional capacity if government\ntargets are met only with BF-BOFs",
                              "Total_net_BOF_capacity_additions_new_projects_1_relining_under_construction" = "New BF-BOF project\n(under construction)",
                              "Total_net_BOF_capacity_additions_new_projects_1_relining_announced_only" = "New BF-BOF project\n(announced)",
                              "Additional_net_BOF_capacity_operating_1_relining" = "Operating BF-BOF capacity, assuming\none BF relining (lifetime of 35 years)",
                              "Total_net_existing_BOF_capacity" = "Operating BF-BOF capacity, assuming\nplants undergo no BF relinings\nafter 2025"))+
  labs(x = "Time period", y = "Global yearly emissions from BF-BOF steel-making (MtCO2/yr)", fill = "Bar Legend", color = "Line Legend")

scale_factor <- 22

p <- p + 
  geom_line(data = data_long_em_cumu, aes(x = factor(index), y = Emissions / scale_factor, group = Category, color = Category), linewidth = 1.3) +#, color = "black", linetype = "dashed") #+
  scale_color_manual(
    values = c(
      "Cumu_oldBOF_1relining" = "grey",
      "Cumu_oldBOF_andnew" = "#b11d36",
      "Cumu_oldBOF" = "#454444",
      "Cumu_oldBOF_new_govtargets" = "#8420f0"
    ),
    labels = c(
      "Cumu_oldBOF_1relining" = "Cumulative CO2 emissions from 2025,\nfrom operating BF-BOFs, if one\nBF relining takes place",
      "Cumu_oldBOF_andnew" = "Cumulative CO2 emissions from 2025,\nfrom operating, under construction and\nannounced BF-BOFs, if one BF relining\ntakes place",
      "Cumu_oldBOF" = "Cumulative CO2 emissions from 2025,\nfrom operating BF-BOFs, if no new\nrelinings take place after 2025",
      "Cumu_oldBOF_new_govtargets" = "Cumulative CO2 emissions from 2025,\nfrom all BF-BOFs, if additional capacity\nis added to meet government targets"
    )
  ) +
    scale_y_continuous( limits = c(0, 3000),
    name = "Global yearly emissions from BF-BOF steel-making\n(MtCO2/yr), barplot",
    sec.axis = sec_axis(~ . * scale_factor, name = "Cumulative CO2 Emissions from 2025,\nfrom BF-BOF steel-making (MtCO2, line plots)")
  ) +
  labs(caption = "*BF-BOF is used as a general term; however, a small subset of included BOF facilities operate\nwithout a BF or rely on alternative iron production methods."
        ) +
  # labs(color = "Line Legend") +
  scale_x_discrete(breaks = x_breaks) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
    text = element_text(size = 12),
    axis.title = element_text(size = 13),
    axis.text = element_text(size = 11),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 10),

    legend.key.height = unit(1.7, "cm"),
    legend.key.width = unit(0.7, "cm"),
    legend.spacing.y = unit(1.6, "cm"),
    legend.margin = margin(8, 8, 8, 8)) +
  guides(
    fill = guide_legend(
      byrow = TRUE,
      title = "Bar Legend",
      keyheight = unit(1.4, "cm"),
      ),
    group = guide_legend(
      byrow = TRUE,
      title = "Line Legend",
      keyheight = unit(2, "cm"),
      )
    )
#add annotations and arrows
p <- p +
  geom_segment(aes(
    x = "2069", xend = "2069",
    y = max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF"]) / scale_factor, 
    yend = max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_1relining"]) / scale_factor
  ), arrow = arrow(length = unit(0.4, "cm")), color = "black") +
  
  geom_segment(aes(
    x = "2069", xend = "2069",
    y = max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_1relining"]) / scale_factor, 
    yend = max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_andnew"]) / scale_factor
  ), arrow = arrow(length = unit(0.4, "cm")), color = "black") +

  geom_segment(aes(
    x = "2069", xend = "2069",
    y = max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_andnew"]) / scale_factor, 
    yend = max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_new_govtargets"]) / scale_factor
  ), arrow = arrow(length = unit(0.4, "cm")), color = "black") +
  
  annotate("text", x = "2069", y = (max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_1relining"]) + 
                                max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF"])) / (2 * scale_factor), 
           label = "Effect of one\nBF relining\nleading to a\nplant lifetime\nof 35 years", hjust = 1.2,vjust = 0.4,
            lineheight = 0.9, size = 3.2) +
  
  annotate("text", x = "2069", y = (max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_1relining"]) + 
                                max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_andnew"])) / (2 * scale_factor), 
           label = "Add planned\nand under\nconstruction\nBF-BOFs", hjust = 1.2,vjust = 0.4,
            lineheight = 0.9, size = 3.2) +
  
  annotate("text", x = "2069", y = (max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_andnew"]) + 
                                max(data_long_em_cumu$Emissions[data_long_em_cumu$Category == "Cumu_oldBOF_new_govtargets"])) / (2 * scale_factor),
            label = "If government\ntargets are reached\nusing new BF-BOFs",
            hjust = 1.05, vjust = 0.6,
            lineheight = 0.9, size = 3.2)
p
# ggsave("figs/BOF_emissions_plot_1relinings.png", width = 11, height = 8, dpi = 300)
```


```{r calc em test}

data_long <- data_long %>%
  filter(Category %in% c(
          "Total_net_existing_BOF_capacity",
          "Additional_net_BOF_capacity_operating_2_relining",
          "Additional_net_BOF_capacity_operating_1_relining",
          "New_BOF_capacity_additions_still_operating_under_construction",
          "New_BOF_capacity_additions_still_operating_announcements",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only",
          "Additional_cumulative_capacity_to_meet_gov_target",
          "index"))

data_long_filtered_em <- data_long %>%
  filter(Category %in% c(
          "Total_net_existing_BOF_capacity",
          "Additional_net_BOF_capacity_operating_2_relining",
          "New_BOF_capacity_additions_still_operating_under_construction",
          "New_BOF_capacity_additions_still_operating_announcements",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only",
          "Additional_cumulative_capacity_to_meet_gov_target",
          "index")) %>%
  filter(index >= 2020) %>%
  # mutate(Emissions = Capacity * 0.8 * 2.3) %>% #0.8 capacity factor, 2.3 tCO2/t steel. Unit is MtCO2/yr
  mutate(Emissions = ifelse(grepl("New_BOF_capacity_additions", Category), Capacity * 0.8 * 2, Capacity * 0.8 * 2.3)) #new additions are BAT = 2 tCO2/t steel


#take wide format to calculate cumulative caps
data_wide_em <- data_long_filtered_em %>%
  select(-Capacity) %>%
  pivot_wider(names_from = Category, values_from = Emissions)

#clean df
data_wide_em[is.na(data_wide_em)] <- 0

#calculate cumulative emissions
data_wide_em_cumu <- data_wide_em %>%
  mutate(Cumu_oldBOF = cumsum(Total_net_existing_BOF_capacity)) %>%
  mutate(Cumu_oldBOF_andnew = cumsum(Total_net_existing_BOF_capacity + 
                                    New_BOF_capacity_additions_still_operating_announcements + 
                                    New_BOF_capacity_additions_still_operating_under_construction)) %>%
  mutate(Cumu_oldBOF_2relining = cumsum(Total_net_existing_BOF_capacity +
                                              New_BOF_capacity_additions_still_operating_announcements + 
                                              New_BOF_capacity_additions_still_operating_under_construction +
                                              Additional_net_BOF_capacity_operating_2_relining)) %>%
    mutate(Cumu_oldBOF_andnew_2relining = cumsum(Total_net_existing_BOF_capacity +
                                              Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction+
                                              Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only+
                                              Additional_net_BOF_capacity_operating_2_relining)) %>%
    mutate(Cumu_additionalGovtargets = Cumu_oldBOF_andnew_2relining +
                                      cumsum(Additional_cumulative_capacity_to_meet_gov_target)) %>%
  select(index, Cumu_oldBOF,Cumu_oldBOF_andnew,Cumu_oldBOF_2relining,Cumu_oldBOF_andnew_2relining, Cumu_additionalGovtargets)

# annoyingly, this needs to be in long format to work
data_long_em_cumu <- data_wide_em_cumu %>%
  pivot_longer(cols = -index, names_to = "Category", values_to = "Emissions")
```
```{r plot complex 2 relinings}

#x ticks
x_breaks <- seq(2020, 2080, by = 5)

data_long_filtered_em <- data_long_filtered_em %>%
  filter(Category %in% c(
          "Total_net_existing_BOF_capacity",
          "Additional_net_BOF_capacity_operating_2_relining",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction",
          "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only",
          "Additional_cumulative_capacity_to_meet_gov_target",
          "index"))

data_long_em_cumu_simple <- data_long_em_cumu %>%
  filter(Category %in% c(
    "Cumu_oldBOF","Cumu_oldBOF_2relining","Cumu_oldBOF_andnew_2relining", "Cumu_additionalGovtargets")
  ) %>%
  mutate(LineCategory = Category)

data_long_filtered_em$Category <- factor(data_long_filtered_em$Category, 
                            levels = c(
                              "Additional_cumulative_capacity_to_meet_gov_target",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction",
                              "Additional_net_BOF_capacity_operating_2_relining",
                              "Total_net_existing_BOF_capacity"))

p <- ggplot(data_long_filtered_em, aes(x = factor(index), y = Emissions, fill = Category)) +
  geom_bar(stat = "identity", data = data_long_filtered_em) +
  scale_fill_manual(values = c("Additional_cumulative_capacity_to_meet_gov_target" = "#8420f0",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction" = "#e41c7d",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only" = "#b11d36",
                              "Additional_net_BOF_capacity_operating_2_relining" = "grey",
                              "Total_net_existing_BOF_capacity" = "#454444"
                              ),
                    labels = c("Additional_cumulative_capacity_to_meet_gov_target" = "Additional capacity if government\ntargets are met only with BF-BOFs",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_under_construction" = "New BF-BOF project\n(under construction)",
                              "Total_net_BOF_capacity_additions_new_projects_2_relining_announced_only" = "New BF-BOF project\n(announced)",
                              "Additional_net_BOF_capacity_operating_2_relining" = "Operating BF-BOF capacity, assuming\ntwo BF relinings (minimum lifetime of\n54 years).",
                              "Total_net_existing_BOF_capacity" = "Operating BF-BOF capacity, assuming\nplants undergo no BF relinings\nafter 2025."))+
  labs(x = "Time period", y = "Global yearly emissions from BF-BOF steel-making (MtCO2/yr)", fill = "Bar Legend", color = "Line Legend") +
  scale_x_discrete(breaks = x_breaks)
  

scale_factor <- 40

p <- p + 
  geom_line(data = data_long_em_cumu_simple, aes(x = factor(index), y = Emissions / scale_factor, group = LineCategory, color = LineCategory), linewidth = 1.3) +#, color = "black", linetype = "dashed") #+
  scale_color_manual(
    values = c(
      "Cumu_oldBOF" = "#454444",
      "Cumu_oldBOF_2relining" = "grey",
      "Cumu_oldBOF_andnew_2relining" = "#b11d36",
      "Cumu_additionalGovtargets" = "#8420f0"
    ),
    labels = c(
      "Cumu_oldBOF" = "Cumulative CO2 emissions from 2020,\nfrom operating BF-BOFs, if no new\nrelinings take place after 2025",
      "Cumu_oldBOF_2relining" = "Cumulative CO2 emissions,\nfrom operating BF-BOFs, if two BF\nrelinings take place",
      "Cumu_oldBOF_andnew_2relining" = "Cumulative CO2 emissions,\nfrom operating, under construction and\nannounced BF-BOFs, if two BF\nrelinings take place",
      "Cumu_additionalGovtargets" = "Cumulative CO2 emissions,\nfrom all BF-BOFs, if additional capacity\nis added to meet government targets"
    )
  ) +
    scale_y_continuous( limits = c(0, 3000),
    name = "Global yearly emissions from BF-BOF steel-making\n(MtCO2/yr), barplot",
    sec.axis = sec_axis(~ . * scale_factor, name = "Cumulative CO2 Emissions from 2020,\nfrom BF-BOF steel-making (MtCO2, lineplots)")
  ) +
  labs(caption = "*BF-BOF is used as a general term; however, a small subset of included BOF facilities operate\nwithout a BF or rely on alternative iron production methods."
        ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
    text = element_text(size = 12),
    axis.title = element_text(size = 13),
    axis.text = element_text(size = 11),
    legend.title = element_text(size = 13),
    legend.text = element_text(size = 10),

    legend.key.height = unit(1.7, "cm"),
    legend.key.width = unit(0.7, "cm"),
    legend.spacing.y = unit(1.6, "cm"),
    legend.margin = margin(8, 8, 8, 8)) +
  guides(
    fill = guide_legend(
      byrow = TRUE,
      title = "Bar Legend",
      keyheight = unit(1.4, "cm"),
      ),
    group = guide_legend(
      byrow = TRUE,
      title = "Line Legend",
      keyheight = unit(2, "cm"),
      )
    )

#add annotations and arrows
p <- p +
  geom_segment(aes(
    x = "2079", xend = "2079",
    y = max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_2relining"]) / scale_factor, 
    yend = max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_andnew_2relining"]) / scale_factor
  ), arrow = arrow(length = unit(0.4, "cm")), color = "black") +
  geom_segment(aes(
    x = "2079", xend = "2079",
    y = max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_andnew_2relining"]) / scale_factor, 
    yend = max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_additionalGovtargets"]) / scale_factor
  ), arrow = arrow(length = unit(0.4, "cm")), color = "black") +
  geom_segment(aes(
    x = "2079", xend = "2079",
    y = max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF"]) / scale_factor, 
    yend = max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_2relining"]) / scale_factor
  ), arrow = arrow(length = unit(0.4, "cm")), color = "black") +
  annotate("text", x = "2080",
          y = (max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_andnew_2relining"]) + 
               max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_2relining"])) / (2 * scale_factor), 
           label = str_wrap("Add planned and under construction BF-BOFs ", width = 17),
           hjust = 1.4, vjust = 0.4,
           lineheight = 0.9, size = 3.5) +
  annotate("text", x = "2080",
          y = (max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_additionalGovtargets"]) + 
               max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_andnew_2relining"])) / (2 * scale_factor), 
          label = str_wrap("If government targets are reached using new BF-BOFs", width = 20),
          hjust = 1.25, vjust = 0.6,
           lineheight = 0.9, size = 3.5) +
  annotate("text", x = "2079",
          y = (max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF_2relining"]) + 
              max(data_long_em_cumu_simple$Emissions[data_long_em_cumu_simple$Category == "Cumu_oldBOF"])) / (2 * scale_factor), 
           label = str_wrap("Effect of two BF relinings leading to a plant lifetime of 54 years", width = 16),
           hjust = 1.2, vjust = 0.4,
           lineheight = 0.9, size = 3.5)
p
# ggsave("figs/BOF_emissions_plot_2relinings.png", width = 11, height = 8, dpi = 300)
```

```{r calc production data}

df_production <- df_production %>%
  rename_all(clean_column_names) %>%
  group_by(Historic_Time) %>%
  summarise(
    Global_steel_production = sum(value))

#clean up age data df: missing ages are 0.
complete_ages <- data.frame(Age = 0:173)
age_data <- merge(complete_ages, age_data, by = "Age", all.x = TRUE)

age_data$Number_of_plants[is.na(age_data$Number_of_plants)] <- 0
age_data$Total_BOF_capacity[is.na(age_data$Total_BOF_capacity)] <- 0

#calculate cumulative capacity (age data)
cumu_cap_age <- age_data %>%
  mutate(Cumu_Total_BOF_capacity = cumsum(Total_BOF_capacity)) %>%
  mutate(Cumu_BOF_capacity_percent = Cumu_Total_BOF_capacity / sum(Total_BOF_capacity) * 100) %>%
  select(Age, Cumu_Total_BOF_capacity, Cumu_BOF_capacity_percent)

```

```{r plot age distribution, basic}

grouping = 5 #years

age_data_grouped <- age_data %>%
  mutate(Age_Group = case_when(
    Age >= 125 ~ "125+",  # Grouping all 81+ together
    TRUE ~ paste0(floor(Age / grouping) * grouping, "-", floor(Age / grouping) * grouping + grouping -1)
  )) %>%
  group_by(Age_Group) %>%
  summarise(
    Total_Plants = sum(Number_of_plants),
    Total_Capacity = sum(Total_BOF_capacity)
  ) %>%
  mutate(Age_Group = factor(Age_Group, levels = c(
    paste0(seq(0, 124, by = grouping), "-", seq(grouping-1, 124 + grouping -1, by = grouping)), "125+"
  )))  # Ensuring correct order

#filter
plot_type <- "Total_Capacity"  # Change to "Total_Capacity" for capacity, "Total_Plants" for number of plants


ggplot(age_data_grouped, aes(x = Age_Group, y = get(plot_type), fill = Age_Group)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  labs(title = "Age Distribution of Plants",
       x = "Age Group (Years)",
       y = ifelse(plot_type == "Total_Plants", "Number of Plants", "Total Capacity (Mtpa)"),
       fill = "Age Group"
       ) +
  guides(fill="none") +
  scale_fill_viridis_d(option = "plasma", direction = -1,) +  # Options: "magma", "plasma", "inferno", "viridis", "cividis"
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  theme_bw()
#ggsave("figs/BOF_age_distribution_plot.png", width = 10, height = 6, dpi = 300)
```

```{r plot age distribution, cumu cap}

grouping = 5 #years

age_data_grouped <- age_data %>%
  mutate(Age_Group = case_when(
    Age >= 125 ~ "125+",  # Grouping all 81+ together
    TRUE ~ paste0(floor(Age / grouping) * grouping, "-", floor(Age / grouping) * grouping + grouping -1)
  )) %>%
  group_by(Age_Group) %>%
  summarise(
    Total_Capacity = sum(Total_BOF_capacity)
  ) %>%
  mutate(Age_Group = factor(Age_Group, levels = c(
    paste0(seq(0, 124, by = grouping), "-", seq(grouping-1, 124 + grouping -1, by = grouping)), "125+"
  )))  # Ensuring correct order

#match cumu capacity data
cumu_cap_grouped <- cumu_cap_age %>%
  mutate(Age_Group = case_when(
    Age >= 125 ~ "125+",
    TRUE ~ paste0(floor(Age / grouping) * grouping, "-", floor(Age / grouping) * grouping + grouping -1)
  )) %>%
  group_by(Age_Group) %>%
  summarise(Cumu_BOF_capacity_percent = max(Cumu_BOF_capacity_percent)) %>%  # Take max per group
  mutate(Age_Group = factor(Age_Group, levels = levels(age_data_grouped$Age_Group)))  # Align factor levels

# join the data
plot_data <- left_join(age_data_grouped, cumu_cap_grouped, by = "Age_Group")

max_cap <- max(plot_data$Total_Capacity)

#aesthetics: extend line
last_x <- length(levels(plot_data$Age_Group))

ggplot(plot_data, aes(x = Age_Group)) +
  geom_bar(aes(y = Total_Capacity, fill = Age_Group), stat = "identity") +
  geom_line(aes(y = Cumu_BOF_capacity_percent * max(Total_Capacity) / 100, group = 1,color = "Cumulative Capacity"), 
           size = 1) +
  geom_segment(aes(x = last_x, xend = last_x +0.4,
                   y = max(max_cap), 
                   yend = max(max_cap)), 
               color = "black", size = 0.9) + 
  scale_y_continuous(
    name = "Total Capacity",
    sec.axis = sec_axis(~ . * 100 / max(max_cap), name = "Cumulative Capacity (%)")
  ) +
  theme_minimal() +
  labs(title = "Age Distribution of Plants",
       x = "Age Group (Years)",
       y = ifelse(plot_type == "Total_Plants", "Number of Plants", "Total Capacity (Mtpa)"),
       fill = "Age Group"
       ) +
  scale_color_manual(name = "Legend", values = c("Cumulative Capacity" = "black")) +
  guides(fill="none") +
  scale_fill_viridis_d(option = "plasma", direction = -1,) +  # Options: "magma", "plasma", "inferno", "viridis", "cividis"
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom") 
  
#ggsave("figs/BOF_age_distribution_plot_wcumu.png", width = 10, height = 6, dpi = 300)
```

```{r plot age distribution, w production}

grouping = 5 #years

age_data_grouped <- age_data %>%
  mutate(Start_Year = 2024 - Age) %>%
  mutate(Start_Year_Group = case_when(
    Start_Year < 1900 ~ "<1900",  # Grouping all 81+ together
    TRUE ~ paste0(floor(Start_Year / grouping) * grouping, "-", floor(Start_Year / grouping) * grouping + grouping -1)
  )) %>%
  group_by(Start_Year_Group) %>%
  summarise(
    Total_Capacity = sum(Total_BOF_capacity)) %>%
  mutate(Start_Year_Group = factor(Start_Year_Group, levels = unique(Start_Year_Group)))


#load production data
df_steel_production <- df_production %>%
  arrange(Historic_Time)
colnames(df_steel_production)[colnames(df_steel_production) == "Historic_Time"] <- "Year"

df_steel_production <- df_steel_production %>%
  mutate(Start_Year_Group = paste0(floor(Year / grouping) * grouping, "-", floor(Year / grouping) * grouping + grouping -1)
  ) %>%
  group_by(Start_Year_Group) %>%
  summarise(Avg_Production = mean(Global_steel_production)/1e6) %>%
  mutate(Start_Year_Group = factor(Start_Year_Group, levels = unique(age_data_grouped$Start_Year_Group)))

#scaling factor
scale_factor <- max(age_data_grouped$Total_Capacity) / max(df_steel_production$Avg_Production)

age_group_positions <- as.numeric(factor(age_data_grouped$Start_Year_Group, levels = levels(age_data_grouped$Start_Year_Group)))

ggplot(age_data_grouped, aes(x = Start_Year_Group)) +
  #highlight sections of interest
  annotate("rect", 
          xmin= age_group_positions[age_data_grouped$Start_Year_Group == "1950-1954"]-0.4,
          xmax=age_group_positions[age_data_grouped$Start_Year_Group == "1970-1974"]+0.4,
          ymin=0, ymax=Inf, alpha=0.4, fill="#e7ab04")+
    annotate("rect", 
          xmin= age_group_positions[age_data_grouped$Start_Year_Group == "1995-1999"]-0.4,
          xmax=age_group_positions[age_data_grouped$Start_Year_Group == "2005-2009"]+0.4,
          ymin=0, ymax=Inf, alpha=0.4, fill="#e7ab04")+
  #plot data
  geom_bar(aes(y = Total_Capacity, fill = Start_Year_Group), stat = "identity") +
  geom_line(data = df_steel_production, aes(x = as.factor(Start_Year_Group), y = Avg_Production * scale_factor, 
                                      group = 1,color = "Avg_Production"), 
           size = 1) +
  scale_y_continuous(
    limits = c(0, 320),
    name = "Total Capacity (Mtpa)",
    sec.axis = sec_axis(~ . / scale_factor, name = "Steel Production (Mt)")
  ) +
  theme_minimal() +
  labs(title = "BF-BOF Plant Start Date",
       x = "Plant Start Date",
       y = "Total Capacity (Mtpa)",
       fill = "Start_Year_Group"
       ) +
  scale_color_manual(name = "Legend", values = c("Historical Steel Production" = "black")) +
  guides(fill="none") +
  scale_fill_viridis_d(option = "plasma", direction = 1) +  # Options: "magma", "plasma", "inferno", "viridis", "cividis"
  theme_bw()+
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom")+
  # Add annotations
  annotate("text", x = "1950-1954", y = max(plot_data$Total_Capacity) * 1.1,
           label = "Post-WW2 BF-BOF\nsurge, driven by Europe,\nJapan, Russia and\nex-USSR countries", color = "black", size = 3.5, hjust = 0.1, vjust = 0) +
    annotate("text", x = "1995-1999", y = max(plot_data$Total_Capacity) * 1.1,
           label = "Recent surge\nof BF-BOFs,\ndriven by China", color = "black", size = 3.5, hjust = 0.2, vjust = 0)
#ggsave("figs/BOF_age_distribution_plot_wprod.png", width = 10, height = 6, dpi = 300)
```

```{r clean production data}
#load production data
df_steel_production <- df_production %>%
  arrange(Historic_Time)
colnames(df_steel_production)[colnames(df_steel_production) == "Historic_Time"] <- "Year"

df_steel_production <- df_steel_production %>%
  mutate(Age = 2024 - Year) %>%
  mutate(Age_Group = case_when(
    Age >= 125 ~ "125+",
    TRUE ~ paste0(floor(Age / grouping) * grouping, "-", floor(Age / grouping) * grouping + grouping -1)
  )) %>%
  group_by(Age_Group) %>%
  summarise(Avg_Production = mean(Global_steel_production)/1e6) %>%
  mutate(Age_Group = factor(Age_Group, levels = unique(age_data_grouped$Age_Group)))

# #there is no data for production before 1900. Therefore, this is NaN. 
# # If you want to make it zero, uncomment the code below
# if (!"125+" %in% df_steel_production$Age_Group) {
#   #add a new row with Age_Group = "125+" and Avg_Production = 0
#   df_steel_production <- df_steel_production %>%
#     add_row(Age_Group = "125+", Avg_Production = 0)
# }

# df_steel_production <- df_steel_production %>%
#   mutate(Age_Group = factor(Age_Group, levels = unique(age_data_grouped$Age_Group)))

```
```{r plot age distribution, regions}

grouping =  5#years

age_data_grouped <- age_data %>%
  mutate(Age_Group = case_when(
    Age >= 125 ~ "125+",  # Grouping all 81+ together
    TRUE ~ paste0(floor(Age / grouping) * grouping, "-", floor(Age / grouping) * grouping + grouping -1)
  )) %>%
  group_by(Age_Group) %>%
  summarise(
    Total_Capacity = sum(Total_BOF_capacity)
  ) %>%
  mutate(Age_Group = factor(Age_Group, levels = c(
    paste0(seq(0, 124, by = grouping), "-", seq(grouping-1, 124 + grouping -1, by = grouping)), "125+"
  )))

# grouping regional age data
age_data_region_grouped <- age_data_region %>%
  mutate(Age_Group = case_when(
    Age >= 125 ~ "125+",
    TRUE ~ paste0(floor(Age / grouping) * grouping, "-", floor(Age / grouping) * grouping + grouping - 1)
  )) %>%
  group_by(Age_Group, Region) %>%
  summarise(
    Regional_Capacity = sum(Total_BOF_capacity)
  ) %>%
  mutate(Age_Group = factor(Age_Group, levels = levels(age_data_grouped$Age_Group)))


#grouping cumu capacity data
cumu_cap_grouped <- cumu_cap_age %>%
  mutate(Age_Group = case_when(
    Age >= 125 ~ "125+",
    TRUE ~ paste0(floor(Age / grouping) * grouping, "-", floor(Age / grouping) * grouping + grouping -1)
  )) %>%
  group_by(Age_Group) %>%
  summarise(Cumu_BOF_capacity_percent = max(Cumu_BOF_capacity_percent)) %>%  # Take max per group
  mutate(Age_Group = factor(Age_Group, levels = levels(age_data_grouped$Age_Group)))  # Align factor levels

# summarize regional capacities for each Age_Group
regional_capacity_sum <- age_data_region_grouped %>%
  group_by(Age_Group) %>%
  summarise(Total_Regional_Capacity = sum(Regional_Capacity))

# merge global and regional data
plot_data <- left_join(age_data_grouped, regional_capacity_sum, by = "Age_Group") %>%
  mutate(Rest_of_World_Capacity = Total_Capacity - ifelse(is.na(Total_Regional_Capacity), 0, Total_Regional_Capacity)) %>%
  select(-Total_Regional_Capacity)

# reshape the data for stacked bar plot
plot_data_long <- plot_data %>%
  gather(key = "Type", value = "Capacity", -Age_Group) %>%
  filter(Type != "Total_Capacity") %>%
  mutate(Type = ifelse(Type == "Rest_of_World_Capacity", "Rest of World", Type))

# add regional data to the long format data
plot_data_long <- bind_rows(
  plot_data_long,
  age_data_region_grouped %>%
    select(Age_Group, Region, Regional_Capacity) %>%
    rename(Type = Region, Capacity = Regional_Capacity)
)

region_labels <- c(
  "CHA" = "China",
  "IND" = "India",
  "JPN" = "Japan",
  "EUR+RUS" = "Europe, Russia and\nex-USSR countries",
  "Rest of World" = "Rest of World"
)
plot_data_long <- plot_data_long %>%
  mutate(Type = recode(Type, !!!region_labels))
#add cumu capacity data
plot_data_long <- left_join(plot_data_long, cumu_cap_grouped, by = "Age_Group")

# #add production data
# df_steel_production <- df_steel_production %>%
#   mutate(Age_Group = factor(Age_Group, levels = levels(plot_data_long$Age_Group)))
# plot_data_long <- left_join(plot_data_long, df_steel_production, by = "Age_Group")

#calculate max production
max_production <- max(plot_data_long$Avg_Production, na.rm = TRUE)
max_capacity <- max(plot_data$Total_Capacity, na.rm = TRUE)
scale_production <- max_capacity / max_production

# # Define x-position for manually drawn y-axis (right side)
# fake_y_axis_x <- length(unique(plot_data_long$Age_Group)) + 1

# # Define tick marks for Steel Production (manually determined)
# steel_tick_values <- seq(0, 2000, length.out = 5)
# scaled_steel_ticks <- steel_tick_values * scale_production 

age_group_positions <- as.numeric(factor(plot_data_long$Age_Group, levels = levels(plot_data_long$Age_Group)))


# plot
ggplot(plot_data_long, aes(x = Age_Group, y = Capacity, fill = Type)) +
  #more annotations: rectangle indicating increase in production
  annotate("rect", 
          xmin= unique(age_group_positions[plot_data_long$Age_Group == "15-19"])-0.4,
          xmax=unique(age_group_positions[plot_data_long$Age_Group == "25-29"])+0.4,
          ymin=0, ymax=Inf, alpha=0.4, fill="#e7ab04")+
    annotate("rect", 
          xmin= unique(age_group_positions[plot_data_long$Age_Group == "50-54"])-0.4,
          xmax=unique(age_group_positions[plot_data_long$Age_Group == "70-74"])+0.4,
          ymin=0, ymax=Inf, alpha=0.4, fill="#e7ab04")+
  geom_bar(stat = "identity") +
  geom_line(aes(y = Cumu_BOF_capacity_percent * max_capacity / 100, group = 1, color = "Cumulative Capacity"), size = 1) +
  # geom_line(aes(y = Avg_Production * (max_capacity / max_production), group = 1, color = "Steel production"), size = 1) +

  # annotation_custom(
  #   grob = linesGrob(gp = gpar(col = "red", lwd = 2)),
  #   xmin = fake_y_axis_x, xmax = fake_y_axis_x, ymin = -17, ymax = max_capacity+150
  # ) +
  # geom_segment(aes(x = fake_y_axis_x, xend = fake_y_axis_x+0.1, 
  #                  y = 0, yend = 0), 
  #              color = "red", size = 0.5) +
  # geom_segment(aes(x = fake_y_axis_x, xend = fake_y_axis_x+0.1, 
  #                  y = 500*(max_capacity / max_production) , yend = 500*(max_capacity / max_production)), 
  #              color = "red", size = 0.5) +
  # geom_segment(aes(x = fake_y_axis_x, xend = fake_y_axis_x+0.1, 
  #                  y = 1000*(max_capacity / max_production) , yend = 1000*(max_capacity / max_production)), 
  #              color = "red", size = 0.5) +
  # geom_segment(aes(x = fake_y_axis_x, xend = fake_y_axis_x+0.1, 
  #                  y = 1500*(max_capacity / max_production) , yend = 1500*(max_capacity / max_production)), 
  #              color = "red", size = 0.5) +
  # geom_segment(aes(x = fake_y_axis_x, xend = fake_y_axis_x+0.1, 
  #                  y = 2000*(max_capacity / max_production) , yend = 2000*(max_capacity / max_production)), 
  #              color = "red", size = 0.5) +
  # # Annotate Steel Production Tick Marks
  # annotate("text", x = fake_y_axis_x + 0.2, y = scaled_steel_ticks, 
  #          label = round(steel_tick_values, 1), color = "red", size = 3, hjust = 0) +
  # # Annotate Steel Production Axis Label
  # annotate("text", x = fake_y_axis_x + 2, y = (max_capacity+80) / 2, 
  #          label = "Steel Production (Mt)", color = "red", size = 4, angle = 270) +
  #text for yellow rects
  annotate("text", x = "50-54", y = max_capacity * 1.1,
          label = "Post-WW2 BF-BOF\nsurge, driven by Europe,\nJapan, Russia and\nex-USSR countries",
          color = "black", size = 3.5, hjust = 0.1, vjust = 0.2) +
  annotate("text", x = "15-19", y = max_capacity * 1.1,
          label = "Recent surge\nof BF-BOFs,\ndriven by China",
          color = "black", size = 3.5, hjust = 0.2, vjust = 0)+
  #expand_limits(x = fake_y_axis_x + 3) +
  theme_minimal() +
  labs(title = "Age Distribution of BF-BOF Plants",
       x = "Age Group (Years)",
       y = "Total Capacity (Mtpa)",
       fill = "Region") +
  guides(fill = guide_legend(title = "Region", nrow = 2)) +
  scale_y_continuous(name = "New annual BF-BOF capacity installed (Mtpa)",
                    limits = c(0, max_capacity+80),
                    sec.axis = sec_axis(~ . * 100 / max_capacity, name = "Cumulative Capacity (%)")) +
  scale_fill_viridis_d(option = "mako", begin = 0.2, end = 0.6, direction = -1) +
  theme_classic() +
  scale_color_manual(name = "Line Legend",
                      values = c("Cumulative Capacity" = "black"
                                #"Steel production" = "red"
                                ),
                      guide = guide_legend(nrow =1)) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        legend.position = "bottom",
        )


# ggsave("figs/BOF_age_distribution_plot_wregions_cumu.png", width = 10, height = 6, dpi = 300)
```