
```{r setup, include = FALSE}
path <- "C:/Users/claraba/Documents/PhD_work/Papers/SteelREMIND/Analysis/"
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(
    root.dir = path
    )


library(ggplot2)
library(gdx)
require(dplyr)
options(dplyr.summarise.inform = FALSE)
library(tidyr)
library(quitte)
library(lusweave)
library(ggsci)
library(pals)
library(stringr)
```

```{r load, echo = FALSE}
#LOAD GDX
# max_lockin <- "inputdata/gdx/PolicyExtended-NPi.gdx"

# max_lockin <- "inputdata/gdx/GreenPolicy_noReliningForSomeRegions-PkBudg820.gdx"

max_lockin <- "inputdata/gdx/PolicyExtended-PkBudg820.gdx"

```

```{R init sets}


###################################################
# CONFIG

gdx <- max_lockin
#name for plotting
name <- "Green Policy 1000"


plotted_years <- c(2030, 2040, 2050)
# plotted_years <- c(2025, 2030, 2035)
# plotted_regions <- c("JPN","CAZ")
plotted_regions <- c('EUR', 'CHA', 'USA', 'IND') 
# plotted_regions <- c('CHA', 'IND') 
fs = 8 # font size

route_names <- tribble(
  ~route,          ~route_name,
  "bfbof",         "BF-BOF",
  "bfbof_ccs",     "BF-BOF CCS",
  "idreaf_ng_ccs", "DRI-EAF NG CCS",
  "idreaf_ng",     "DRI-EAF NG",
  "idreaf_h2",     "DRI-EAF H2",
  "seceaf",        "Scrap EAF",
  "bfbof_ccs_r",   "BF-BOF CCS retrofit"
)

# component_names <- tribble(
#   ~component,      ~component_name, ~color,
#  "CO2",           "Emission Cost", "#444444",
#  # "inje",          "CCS Injection", "#999999",
#  "feels",         "Electricity",   "#a2dd85",
#  "feh2s",         "Hydrogen",      "#85b3dd",
#   "fegas",         "Non-H2 Gases",  "#dda185",
#   "fehos",         "Liquids",       "#b185dd",
#   "fesos",         "Solids",        "#c4b962",
#   "eafscrap",      "EAF Scrap",         "#225577",
#   "bofscrap",      "BOF Scrap",     "#2a6790",
#   "ironore",       "Iron Ore",      "#774444",
#   "dripell",       "DRI Pellets",   "#447744",
#   "OPEX",          "OPEX",          "#cccccc",
#   "CAPEX",         "CAPEX",         "#555555"
# )

component_names <- tribble(
  ~component,      ~component_name, ~color,
 "CO2",           "Emission Cost", "#444444",
 # "inje",          "CCS Injection", "#999999",
 "feels",         "Electricity",   "#d7cb1b",
 "feh2s",         "Hydrogen",      "#33efef",
  "fehos",         "Liquids",       "#11522b",
  "fesos",         "Solids",        "#76512c",
  "fegas",         "Non-H2 Gases",  "#85b3dd",
  "eafscrap",      "EAF Scrap",         "#a45353",
  # "bofscrap",      "BOF Scrap",     "#9f5b5b",
  "bofscrap",      "BOF Scrap",     "#fe0404",
  "ironore",       "Iron Ore",      "#7e433d",
  "dripell",       "DRI Pellets",   "#7d2222",
  "OPEX",          "OPEX",          "#cccccc",
  "CAPEX",         "CAPEX",         "#7b7878"
)

    
region_names  <- tribble(
  ~region, ~region_name,
  # 'JPN',   'Japan',
  # 'CAZ',   'Australia*'
  'EUR',   'EU',
  'CHA',   'China',
  'USA',   'USA',
  'IND',   'India'
)

###################################################
# READ IN GENERIC SETS



tePrc <- readGDX(gdx,"tePrc")
# tePrcAll <- append(tePrc, "ccsinje") ## do not use ccsinje cost anymore (is included in vm_co2capture cost)
tePrcAll <- tePrc

tePrc2opmoPrc <- as.data.frame(readGDX(gdx,"tePrc2opmoPrc")) %>% 
  rename(all_te = tePrc)

entyFE <- as.vector(readGDX(gdx, name="entyFE"))

t <- readGDX(gdx,"ttot")
t <- as.numeric(t[t >= 2005 & t <= 2100])

regi <- readGDX(gdx,"regi")


```

```{R calc costCO2 and costfuel (energy)}
###################################################
# ENERGY 

# CARBON COST: Carbon price times average emission per FE (which is determined by SE shares, i.e. fossil/bio/synfuel)

df.priceCO2 <- as.quitte(readGDX(gdx,name=c("p_priceCO2","pm_priceCO2"),format="first_found")) %>%
    select(region, period, value) %>%
    # where carbon price is NA, it is zero
    # convert from USD2005/tC CO2 to USD2015/tCO2
    mutate(value = ifelse(is.na(value), 0, value /1000.)) %>% # carbon price i given in $/tC instead of remind units (tn $/GtC)
    filter(period %in% t) %>%
    rename(priceCO2 = value) 

df.emiFac <- as.quitte(readGDX(gdx, name="pm_emifac", restore_zeros = F)) %>% 
  filter(all_enty1 %in% entyFE, all_enty2 == "co2", period %in% t) %>%
  select(period, region, all_enty, all_enty1, value) %>%
  rename(entySE = all_enty, entyFE = all_enty1, emiFac = value) 

df.demFe <- as.quitte(readGDX(gdx, "vm_demFeSector_afterTax", field = "l", restore_zeros = F)[,t,]) %>%
  # dimensions: vm_demFeSector_afterTax(ttot,regi,entySE,entyFE,"indst",emiMkt)
  filter(all_enty1 %in% entyFE, emi_sectors == "indst", all_emiMkt == "ETS", value > 0.) %>%
  select(period, region, all_enty, all_enty1, value) %>%
  rename(demFE = value, entySE = all_enty, entyFE = all_enty1) 
  
df.emiFacAvg <- df.demFe %>% 
  left_join(df.emiFac, by=c("region", "period", "entySE", "entyFE")) %>%
  mutate(emiFac = if_else(is.na(emiFac), 0., emiFac), emiTot = demFE * emiFac) %>%
  group_by(period, region, entyFE) %>%
  summarise(emiTot = sum(emiTot), demFE = sum(demFE)) %>%
  ungroup() %>%
  filter(demFE > 0.) %>%
  mutate(emiFac = emiTot / demFE) %>%
  select(-emiTot, -demFE)
  

# FE tax per unit of burnt FE
df.FeEmiCost <- df.priceCO2 %>% 
  right_join(df.emiFacAvg, by=c("period", "region")) %>% 
  mutate(FeEmiCost = priceCO2 * emiFac) %>%
  select(-emiFac, -priceCO2)


#### OPTION 1: directly take FE price
# df.priceFuel <- as.quitte(readGDX(gdx, "pm_FEPrice", restore_zeros = F)) %>%
#   filter(sector == "indst", emiMkt == "ETS", value > 0., period %in% t) %>%
#   select(region, period, all_enty, value) %>%
#   rename(entyFE = all_enty, priceFuel = value)

#### OPTION2: take price differentiated by SE, then take weighted sum according to SE shares.
df.priceFuel <- as.quitte(readGDX(gdx, "p_FEPrice_by_SE_Sector_EmiMkt", restore_zeros = F)) %>%
  # filter(sector == "indst", emiMkt == "ETS", value > 0., period %in% t) %>%
  filter(sector == "indst", emiMkt == "ETS", period %in% t) %>%
  select(region, period, entySe, all_enty, value) %>%
  rename(entySE = entySe, entyFE = all_enty, priceFuel = value)
df.demFETotal = df.demFe  %>% 
  group_by( region, period, entyFE) %>% 
  summarize(demFETotal = sum(demFE)) %>%
  ungroup
df.SEShares = df.demFe  %>%
  left_join(df.demFETotal, by=c("region", "period", "entyFE")) %>%
  mutate(SEShare = demFE / demFETotal) %>%
  select(-demFE, -demFETotal)
df.priceFuel <- df.priceFuel %>%
  left_join(df.SEShares, by=c("region", "period", "entySE", "entyFE")) %>%
  mutate(priceFuel = priceFuel * replace_na(SEShare, 0.)) 

#TODO: plot. Also need to get the Co2 emission cost to substract from fossils
df.biosolidsfrac <- df.priceFuel %>% filter(entyFE == "fesos")  %>% 
# Check units. This does not seem correct (something wrong with emicosts?)
# or instead simply use SE costs to get a rough idea
  left_join(df.emiFac, by=c("region", "period", "entySE", "entyFE")) %>%
  left_join(df.priceCO2, by = c("region", "period")) %>%
  mutate(emicost = ifelse(is.na(emiFac), 0, emiFac) * priceCO2) %>%
  select(-emiFac, -priceCO2)


df.priceFuel <- df.priceFuel  %>% 
  group_by(region, period, entyFE) %>% 
  summarize(priceFuel = sum(priceFuel)) %>%
  ungroup


# Subtract FE tax from fuel price
## comment out if you want to use only FE prices, no CO2
df.priceFuel <- df.priceFuel %>%
  left_join(df.FeEmiCost, by=c("region", "period", "entyFE")) %>%
  mutate(priceFuel = priceFuel - ifelse(is.na(FeEmiCost), 0., FeEmiCost)) %>%
  select(-FeEmiCost)

df.specFeDem <- as.quitte(readGDX(gdx,name=c("pm_specFeDem"),format="first_found",restore_zeros = F)) %>% 
  filter(value > 0., period %in% t) %>%
  select(region, period, all_enty, all_te, opmoPrc, value) %>%
  rename(entyFE = all_enty, specFeDem = value)


df.costFuel = df.specFeDem %>% 
  left_join(df.priceFuel, by = c("region", "period", "entyFE")) %>% 
  mutate(value = specFeDem * priceFuel) %>% 
  mutate(component = entyFE) %>% 
  select(-priceFuel, -specFeDem)


df.costCO2 <- df.specFeDem %>% 
  left_join(df.FeEmiCost, by = c("region", "period", "entyFE")) %>% 
  mutate(value = specFeDem * FeEmiCost) %>% 
  filter(value > 0.) %>% 
  group_by( region, period, all_te, opmoPrc) %>%
  summarize(value = sum(value)) %>%
  ungroup %>%
  mutate(component = "CO2")


# subtract emission tax saved by capture

### OPTION 1: co2 price
# df.costCO2 <- df.costCO2 %>% 
#   left_join(df.priceCO2, by = c("region", "period")) %>% 
#   mutate(value = value - ifelse(all_te %in% c("bfcc", "idrcc"), priceCO2, 0.)) %>%
#   select(-priceCO2)

### option 2: vm_emiIndCCS price
q37_emiCCPrc <- as.quitte(readGDX(gdx,name=c("q37_emiCCPrc"),format="first_found", field = "m", restore_zeros = F)) %>%
  filter(emiInd37 == "co2steel", period %in% t) %>%
  select(-scenario, -model, -variable, -unit, -emiInd37) 
  
qm_budget <- as.quitte(readGDX(gdx,name=c("qm_budget"),format="first_found", field = "m", restore_zeros = F)) %>%
  select(-scenario, -model, -variable, -unit)
df.priceSavedCO2 <- q37_emiCCPrc %>% 
  rename(emi = value) %>%
  left_join(qm_budget, by=c("period", "region")) %>%
  mutate(priceSavedCO2 = -emi / value) %>% 
  select(-emi, -data, -value)
  
df.costCO2 <- df.costCO2 %>% 
  left_join(df.priceSavedCO2, by = c("region", "period")) %>% 
  mutate(value = value - ifelse(all_te %in% c("bfcc", "idrcc"), priceSavedCO2, 0.)) %>%
  select(-priceSavedCO2)


````

```{R calc mat demand and capex}
###################################################
# MATERIAL
# calculates cost of material required
# for DRIEAF: dri pellets, dri iron. If secondary EAF, additional scrap.
# for BFBOF: iron ore, pig iron, BOF scrap (very very small)

specMatDem <- as.quitte(readGDX(gdx,name=c("p37_specMatDem"),format="first_found",restore_zeros = F)) %>% 
  filter(value > 0.) %>%
  select(mat, all_te, opmoPrc, value) %>%
  rename( specMatDem = value)

priceMat <- as.quitte(readGDX(gdx,name=c("p37_priceMat"),format="first_found",restore_zeros = F)) %>% 
  filter(value > 0.) %>%
  select(all_enty, value) %>%
  rename( priceMat = value, mat = all_enty)

df.costMat = specMatDem %>% 
  left_join(priceMat, by = "mat") %>% 
  mutate(value = specMatDem * priceMat) %>% 
  filter(value > 0.) %>%
  rename(component = mat) %>% 
  select(-specMatDem, -priceMat) %>%
  crossing(t, regi) %>% 
  rename(period = t, region = regi)

###################################################
# AUXILIARY FACTORS FOR CAPEX AND OMF: lifetime and annuity

df.capFac <- as.quitte(readGDX(gdx, "vm_capFac", field="l", restore_zeros = F)[,t,]) %>%
    select(region, period, all_te, value) %>%
    filter(all_te %in% tePrcAll ) %>%
    rename(capFac = value)

# add capacity 
df.cap <- as.quitte(readGDX(gdx, "vm_cap", field="l", restore_zeros = F)[,t,]) %>%
    select(region, period, all_te, rlf, value) %>%
    filter(all_te %in% tePrcAll ) %>%
    rename(cap = value)

  
wacc <- 0.045

lifetime <- readGDX(gdx, name="fm_dataglob", restore_zeros = F)[,,"lifetime"][,,tePrcAll][,,"lifetime"]

df.discFac <- as.quitte(lifetime) %>%
  select(all_te, value) %>%
  rename(lifetime = value) %>%
  mutate( discFac = wacc * (1+wacc)^lifetime/(-1.+(1+wacc)^lifetime))%>%
  select(all_te, discFac)


###################################################
# CAPEX and OPEX

df.CAPEX <- as.quitte(readGDX(gdx, "vm_costTeCapital", field = "l", restore_zeros = F)[,t,tePrcAll]) %>%
    select(region, period, all_te, value) %>%
    mutate(component = "CAPEX") %>%
    left_join(df.capFac, by=c("region", "period", "all_te")) %>%
    mutate(value = value / capFac) %>%  # conversion from MW/a to MWh/a
    select(-capFac)

df.OMF <- as.quitte(readGDX(gdx, "pm_data", restore_zeros = F)[,,"omf"]) %>%
    select(region, all_te, value) %>%
    filter(all_te %in% tePrcAll, value > 0.) %>%
    # mutate(component = "OMF") %>% 
    full_join(df.CAPEX %>% 
                rename(CAPEX = value) %>%
                select(region, period, all_te, CAPEX),
              by=c("region", "all_te")) %>%
    mutate(value = value * CAPEX ) %>% 
    select(-CAPEX)
   
df.OMV <- as.quitte(readGDX(gdx, "pm_data", restore_zeros = F)[,,"omv"]) %>%
    select(region, all_te, value) %>%
    filter(all_te %in% tePrcAll, value > 0.)

df.OPEX <- bind_rows(df.OMF, df.OMV) %>% 
  group_by( region, period, all_te) %>% 
  summarize(value = sum(value)) %>%
  ungroup  %>%
  mutate(component = "OPEX") %>% 
  full_join(tePrc2opmoPrc, by="all_te")

# multiply with discount factor (has to be done after calculating OMF)
df.CAPEX <- df.CAPEX %>% 
  left_join(df.discFac, by="all_te") %>% 
  mutate(value = value * discFac) %>% 
  select(-discFac) %>% 
  full_join(tePrc2opmoPrc, by="all_te")

###################################################
# CCS INJECTION 
# 
# df.capexInj <- df.CAPEX %>%
#   filter(all_te == "ccsinje") %>%
#   select(region, period, value) %>%
#   rename(CAPEX = value)
# 
# df.opexInj <- df.OPEX %>%
#   filter(all_te == "ccsinje") %>%
#   select(region, period, value) %>%
#   rename(OPEX = value)
# 
# df.costInj = df.capexInj %>% 
#   left_join(df.opexInj, by = c("period", "region")) %>% 
#   mutate(value = CAPEX + OPEX,
#          component = "inje") %>% 
#   select(region, period, value, component)
# 
# 
# df.costInj = bind_rows(
#   df.costInj %>% mutate(all_te = "bfcc",  opmoPrc = "standard"), 
#   df.costInj %>% mutate(all_te = "idrcc", opmoPrc = "ng")
# )
# 
# # remove inje from CAPEX and OPEX dataframes; add opmoPrc to Capx and OPEX df's
# df.CAPEX = df.CAPEX %>% 
#   filter(all_te != "ccsinje") %>% 
#   full_join(tePrc2opmoPrc, by="all_te")
# df.OPEX = df.OPEX  %>% 
#   filter(all_te != "ccsinje") %>% 
#   full_join(tePrc2opmoPrc, by="all_te")

```

```{R join all components}
###################################################
# JOIN COMPONENTS

lcop <- bind_rows(df.costMat, 
                  df.costFuel,
                  #df.costInj,
                  # comment out below if not wanting to show Co2 prices
                  df.costCO2,
                  df.CAPEX,
                  df.OPEX
                  )


###################################################
# JOIN PROCESSES
  
  
tePrc2route <- as.data.frame(readGDX(gdx,name=c("tePrc2route"),format="first_found",restore_zeros = F)) %>%
  rename(all_te = tePrc)

o37_relativeOutflow <- as.quitte(readGDX(gdx,name=c("o37_relativeOutflow"),format="first_found",restore_zeros = F)) %>% 
  select(all_te, opmoPrc, region, period, value) %>% 
  filter(value > 0.) %>%
  rename(relativeOutflow = value)


lcop <- lcop %>% 
  full_join(tePrc2route, by=c("all_te","opmoPrc")) %>% # TODO: check eaf-pri (3 routes)
  left_join(o37_relativeOutflow, by=c("all_te", "opmoPrc", "period", "region")) %>%
  mutate(value = value * relativeOutflow)%>% 
  mutate(value = value * 1000) #in USD2017


###################################################
## PRICES 
## currently not using

# q37_mat2ue <- as.quitte(readGDX(gdx,name=c("q37_mat2ue"),format="first_found", field = "m", restore_zeros = F)) %>%
#   select(-scenario, -model, -variable, -unit)
# qm_budget <- as.quitte(readGDX(gdx,name=c("qm_budget"),format="first_found", field = "m", restore_zeros = F)) %>%
#   select(-scenario, -model, -variable, -unit)

# priceSteel <- q37_mat2ue %>% 
#   filter(period %in% t) %>%
#   rename(mat2ue = value) %>%
#   left_join(qm_budget, by=c("period", "region")) %>%
#   mutate(value = -mat2ue / value) %>% 
#   select(-mat2ue, -data) %>% 
#   mutate(value = value  * 1000)

# pricePrim <- priceSteel %>% 
#   filter(all_in == "ue_steel_primary") %>%
#   rename(pricePrim = value) %>% 
#   select(-all_in)
  
# priceSec <- priceSteel %>% 
#   filter(all_in == "ue_steel_secondary") %>%
#   rename(priceSec = value) %>% 
#   select(-all_in)


```

```{R}
########################
## TAKE AVG VALUES
### add averaging routine: value given in 2025 is actually averaged LCOP over 2025+ lifetime asset 


add_5y_timesteps <- function(df) {
  
  full_timesteps <- seq(2005, 2100, by=5)

  te2route <- tePrc2route %>%
    select(all_te, route)

  df_expanded <- expand.grid(
      region = unique(df$region),
      period = full_timesteps,
      component = unique(df$component),
      route = unique(df$route),
      all_te = unique(df$all_te))


  full_df <- df_expanded %>%
    left_join(df, by = c("region", "period", "component", "all_te", "route")) %>%
    group_by(region,route,all_te,component) %>%
    arrange(period) %>%
    mutate(value = ifelse(is.na(value), lead(value), value)) %>% 
    ungroup()

  full_df <- full_df %>%
    inner_join(te2route, by=c("all_te", "route")) %>%
    #remove rows where value is NA
    # for example, the matching gives bof scrap rows for drieaf, which are then NA 
    filter(!is.na(value))
}

lcop_avg <- lcop %>% 
  select(-relativeOutflow, -opmoPrc, -entyFE) 

#fill in the missing time steps
lcop_avg <- add_5y_timesteps(lcop_avg)

#add lifetime info and end date
lcop_avg <- lcop_avg %>%
  left_join(as.quitte(lifetime) %>%
      select(all_te, value) %>%
    rename(lifetime = value), by="all_te") %>% 
  mutate(end_period = period + lifetime) %>%
  #we have no info after 2100. The more interesting period is earlier anyways
  filter( period >= 2020) %>% 
  select(-lifetime) %>% 
  #calculate mean values over lifetime of the plant
  rowwise() %>%
  mutate(avg_value = mean(
    lcop_avg$value[
      lcop_avg$region == region &
      lcop_avg$route == route &
      lcop_avg$component == component &
      lcop_avg$all_te == all_te &
      lcop_avg$period >= period & 
      lcop_avg$period <= end_period]
    )
  ) %>%
  select(-value, -end_period) %>%
  rename(value = avg_value)

```

```{R}

###################################################
# PREPARE FOR PLOTTING

## uncomment if you want to plot average lcop value over plant lifetime
lcop_plot <- lcop_avg %>%
# lcop_plot <- lcop %>%
  left_join(route_names, by="route") %>% 
  select(-route) %>% 
  rename(route = route_name) %>%
  left_join(component_names, by="component") %>%
  select(-component) %>%
  rename(component = component_name) %>%
  group_by(period, region, component, route) %>%
  summarize(value = sum(value), color=first(color)) %>%
  ungroup %>%
  mutate(value = pmax(value, 0.)) # sweep negative prices under the rug

### add BF-BOF-CCS retrofit
new_rows <- lcop_plot %>%
  filter(route == "BF-BOF CCS") %>%
  mutate(route = "BF-BOF CCS retrofit")

# Adjust the CAPEX values for retrofit
capex_adjustment <- lcop_plot %>%
  filter(route == "BF-BOF CCS", component == "CAPEX") %>%
  left_join(lcop_plot %>% filter(route == "BF-BOF", component == "CAPEX"),
            by = c("period", "region"), suffix = c("_ccs", "_bof")) %>%
  select(-component_bof, route_bof, color_bof) %>%
  mutate(value = value_ccs - value_bof) %>%
  mutate(component = component_ccs) %>%
  mutate(color = color_ccs) %>%
  mutate(route = "BF-BOF CCS retrofit") %>%
  select(period, component, region, route, value, color)

# Replace the CAPEX rows in new_rows with the adjusted values
new_rows <- new_rows %>%
  filter(component != "CAPEX") %>%
  bind_rows(capex_adjustment)

lcop_plot <- bind_rows(lcop_plot, new_rows)

## BElow is only for retrofit comparison
# #make CAPEX 0 for route BF-BOF
# lcop_plot <- lcop_plot %>%
#   mutate(value = ifelse(route == "BF-BOF" & component == "CAPEX", 0., value))

### continue with lcop plot

lcop_plot$component <- factor(lcop_plot$component, levels=unique(component_names$component_name))

lcop_plot <- lcop_plot %>%
  filter(region %in% plotted_regions, period %in% plotted_years) %>% 
  mutate(route_id = route %>% as.factor() %>% as.numeric()) %>% 
  mutate(year_id = period %>% as.factor() %>% as.numeric()) %>% 
  mutate(n_routes = max(route_id)) %>%
  mutate(year_label_pos = (n_routes+2) * year_id) %>% 
  mutate(pos = year_label_pos + route_id - (n_routes+1)/2.) %>% 
  select(-year_id, -route_id, -n_routes) %>%
  left_join(region_names, by="region") %>% 
  select(-region) %>% 
  rename(region = region_name) %>%
  mutate(region = factor(region, levels=unique(region_names$region_name))) 

route_label <- lcop_plot %>% 
  select(route, pos, region) %>% 
  unique()

year_label <- lcop_plot %>% 
  select(period, year_label_pos, region) %>% 
  unique()

routes = unique(route_names$route_name)

# currently not interested in the prices
# priceSteel_plot <- pricePrim %>% 
#   left_join(priceSec, by=c("region", "period")) %>%
#   filter(region %in% plotted_regions, period %in% plotted_years) %>% 
#   left_join(region_names, by="region") %>% 
#   select(-region) %>% 
#   rename(region = region_name) %>%
#   mutate(region = factor(region, levels=unique(region_names$region_name))) %>%
#   cross_join(as.data.frame(routes)) %>% 
#   mutate(price = ifelse(routes == 'Scrap EAF', priceSec, pricePrim)) %>% 
#   mutate(label = ifelse(routes == 'Scrap EAF', 'Secondary', 'Primary')) %>% 
#   select(-pricePrim, -priceSec) %>%
#   rename(route = routes) %>%
#   left_join(lcop_plot %>% select(region, period, route, pos), by=c("region", "period", "route")) %>% 
#   select(-route) %>% 
#   mutate(shape = label %>% as.factor())
  

xmin <- min(lcop_plot$pos) - 1.
xmax <- max(lcop_plot$pos) + 1.


###################################################
# VARIABLE FILTER:
### setting some inputs and regions  to zero allows to build up plots step by step in presentations

  
component_names <- component_names %>%
  filter(color %in% unique(lcop_plot$color))


# comp_non_zero = c("Scrap", "Iron Ore", "DRI Pellets", "OPEX", "CAPEX")
# comp_non_zero = c("Electricity", "Hydrogen", "Non-H2 Gases", "Liquids", "Solids", "Scrap", "Iron Ore", "DRI Pellets", "OPEX", "CAPEX")
comp_non_zero = c("Emission Cost", "Electricity", "Hydrogen", "Non-H2 Gases", "Liquids", "Solids", "Scrap", "Iron Ore", "DRI Pellets", "OPEX", "CAPEX")

# regi_non_zero = c("EU")
# regi_non_zero = c("EU", "China", "USA")
regi_non_zero = c("EU", "China", "USA", "India")

lcop_plot <- lcop_plot %>% 
  filter(component %in% unique(component_names$component_name)) # %>%
  # mutate(value = ifelse(region %in% regi_non_zero, value, 0.)) %>% 
  # mutate(value = ifelse(component %in% comp_non_zero, value, 0.))


#currently no prices plot
# priceSteel_plot <- priceSteel_plot %>%
#   filter(region %in% regi_non_zero)

###################################################
# PLOT

# p.lcop <- ggplot() +
# p.lcop <- ggplot() +
#   geom_bar(data=lcop_plot, position="stack", stat="identity",
#            aes(x = pos, y = value, fill=component)) +
#   xlim(xmin, xmax) +
#   ylim(-601.,1390) +
#   facet_wrap(~region) +
#   scale_fill_manual(values=unique(component_names$color)) +
#   geom_text(data=route_label, aes(label = route, hjust = 1.), x = route_label$pos, y = -8., angle = 90, size =fs/4) +
#   geom_text(data=year_label, aes(label = period), x = year_label$year_label_pos, y = -600., size = fs/2.5, parse = T) +
#   geom_point(data=priceSteel_plot, aes(x = pos, y = price, shape=shape)) +
#   scale_shape_manual(values=unique(priceSteel_plot$shape), labels=unique(priceSteel_plot$label)) +
#   theme(text=element_text(size=fs),
#         axis.title.x=element_blank(),
#         axis.text.x=element_blank(),
#         axis.ticks.x=element_blank(),
#         axis.text.y=element_text(size=fs),
#         strip.text = element_text(size = 1.2 * fs)) +
#   labs(y = "LCOP [$/t]", fill="Cost Component", shape="Price")
  # labs(y = "LCOP [$/t]", fill="Cost Component")

# ggsave(filename = "all_routes.png", width = 12, height = 6, device='png', dpi=300)

# p.lcop

```


```{R}
##############################
# PLOT BOTH ROUTES
lcop_plot
lcop_2r <- lcop_plot %>%
  # filter(route %in% c("BF-BOF CCS retrofit", "DRI-EAF H2", "BF-BOF", "DRI-EAF NG")) %>%
  filter(route %in% c("DRI-EAF H2", "BF-BOF","BF-BOF CCS", "DRI-EAF NG", "Scrap EAF")) %>%
  mutate(pos = period %>% as.factor() %>% as.numeric(),
          route = as.factor(route))

#test to plot bars next to noe another
lcop_2r <- lcop_2r %>%
  # mutate(pos_offset = ifelse(route == "DRI-EAF H2", pos + 0.15, pos - 0.15))
  # mutate(pos_offset = ifelse(route == "DRI-EAF H2", pos + 0.3, ifelse(route == "BF-BOF", pos - 0.3, ifelse(route == "DRI-EAF NG", pos + 0.1, pos - 0.1))))
  mutate(pos_offset = ifelse(route == "DRI-EAF H2", pos + 0.225, ifelse(route == "BF-BOF", pos - 0.225, ifelse(route == "DRI-EAF NG", pos + 0.075, ifelse(route == "BF-BOF CCS", pos - 0.075, pos + 0.375)))))

label_data <- lcop_2r %>%
  group_by(route, pos_offset, region) %>%
  summarize(y = sum(value), .groups = "drop") %>%
  # mutate(label = gsub(' ', '\n', route))
  # mutate(label = str_wrap(route, width = 20))
  mutate(label = route)

year_label <- year_label %>% 
  mutate(pos = period %>% as.factor() %>% as.numeric())
xmin <- min(lcop_2r$pos) - 0.7
xmax <- max(lcop_2r$pos) + 0.7


unique_component_names <- unique(as.character(component_names$component_name))

lcop_2r$component <- factor(lcop_2r$component, levels=unique_component_names)

component_names_1r <- component_names %>%
  #filter(color %in% unique(lcop_2r$color))
  filter(component_name %in% unique_component_names)

lcop_2r <- lcop_2r %>%
  arrange(factor(component, levels = rev(unique_component_names)))


p.drieaf <- ggplot() +
  geom_bar(
    data=lcop_2r,
    aes(x = pos_offset, y = value, fill=factor(component, levels = unique_component_names), group = route),
    position="stack",
    stat="identity", 
    width=0.15,
    ) + 
  scale_fill_manual(
    values = setNames(component_names_1r$color, unique_component_names),
    breaks = unique_component_names
  ) +
  facet_wrap(~region) +
  xlim(xmin, xmax)  +
  ylim(-51.,2200.) +
  geom_text(data=year_label, aes(label = period), x = year_label$pos, y = -70., size = 2, parse = T) +
  geom_text(
    data = label_data,
    aes(
      x = pos_offset,
      y = y +20,  
      label = str_wrap(label,10),
      angle = 90
    ),
    size = 1.5,
    lineheight = 0.8,
    hjust = 0, 
    color = "black"
  ) +
  theme(text=element_text(size=fs),
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_text(size=fs),
        strip.text = element_text(size = 0.8 * fs)) + 
  labs(title = "Average LCOP over the lifetime of a newly built plant in a given year,\nfor different production pathways (Extended lock-in)",
      y = "LCOP [$/t]",
      fill="Cost Component")

# ggsave(filename = "./figs_temp/lcop_byroute_lockin.png", width = 6, height = 5, device='png', dpi=300)


p.drieaf


```
```{R}

###################################################
# PREPARE FOR PLOTTING

#HERE: calculate average lcop for ALL steel (primary and secondary, weighted by route production)


#tePrc2route
df.outflowPrc <- as.quitte(readGDX(gdx, "vm_outflowPrc", field = "l", restore_zeros = F)[,t,]) %>%
    filter(all_te %in% tePrcAll) %>%
    select(region, period, all_te, value, opmoPrc) %>%
    rename(outflowPrc = value) %>%
    # left_join(tePrc2route, by = c("all_te", "opmoPrc")) %>% 
    left_join(o37_relativeOutflow, by=c("region", "period", "all_te", "opmoPrc")) %>% 
    mutate(value = outflowPrc / relativeOutflow)

#calculate production fractions

# eaf_techs <- c("bf", "idr")
ccs_techs <- list(c("bf", "bfcc"), c("idr", "idrcc"))
steel_techs <- c("bof", "eaf")

#precompute values
ccs_lookup <- df.outflowPrc %>%
  #h2 dri does not have ccs, keep only ng
  filter(opmoPrc != "h2") %>%
  group_by(region, period, all_te) %>%
  summarize(value = sum(value)) %>%
  filter(all_te %in% unlist(ccs_techs)) %>%
  pivot_wider(names_from = all_te, values_from = value, values_fill = 0.) %>%
  rename(bf_val = bf, 
         bfcc_val = bfcc, 
         idr_val = idr, 
         idrcc_val = idrcc) %>%
  select(region, period, bf_val, bfcc_val, idr_val, idrcc_val) %>% 
  #drop dupplicates
  distinct(region, period, .keep_all = TRUE)

#calculate production fractions
df.prod_frac <- df.outflowPrc %>% 
  left_join(ccs_lookup, by=c("region", "period")) %>%
  group_by(region,period) %>%
  mutate(
    eaf_sum = sum(value[all_te == "idr"]),
    steel_sum = sum(value[all_te %in% steel_techs]),
    # for idr, there are two operational possibilites: h2 and ng. Then, ccs comes on top
    iron_frac = ifelse(all_te == "idr", value / eaf_sum, 1.),
    iron_frac = ifelse(is.na(iron_frac), 0., iron_frac), # in case of no idr production, set to 0.

    steel_frac = ifelse(all_te %in% steel_techs, value / steel_sum, 1.),
    ccs_frac = case_when(
      all_te == "bf" ~ 1 - (bfcc_val / bf_val),
      all_te == "idr" & opmoPrc != "h2"  ~  1-  (idrcc_val/idr_val),
      all_te == "bfcc" ~ (bfcc_val / bf_val),
      all_te == "idrcc" ~ (idrcc_val/idr_val),
      # most other techs have no ccs, so set to 1.  as we will multiply iron_frac and steel_frac with ccs_frac
      TRUE ~ 1.
    ),
    ccs_frac = ifelse(is.na(ccs_frac), 0., ccs_frac) # in case of no ccs production, set to 0.
    ) %>%
  ungroup() %>% 
  select(region, period, all_te, opmoPrc, value, iron_frac, steel_frac, ccs_frac) %>%
  left_join(tePrc2route, by=c("all_te", "opmoPrc")) %>% 
  filter(!(all_te == "bf"&route == "bfbof_ccs")) %>% #hack to count CCS tech fractions properly
  filter(!(all_te == "idr" & route == "idreaf_ng_ccs"))%>% #hack to count CCS tech fractions properly
  mutate(frac = iron_frac * steel_frac * ccs_frac) %>%
  group_by(region, period, route) %>%
  # multiply ccs component with iron and steel component to get total route production factor
  summarise(frac = prod(frac))


lcop_weighted <- lcop %>%
  left_join(df.prod_frac, by=c("region", "period", "route")) %>%
  mutate(value = value * frac)  %>%
  select(-frac)

lcop_plot <- lcop_weighted %>%
  left_join(route_names, by="route") %>% 
  select(-route) %>% 
  rename(route = route_name) %>%
  left_join(component_names, by="component") %>%
  select(-component) %>%
  rename(component = component_name) %>%
  group_by(period, region, component, route) %>%
  summarize(value = sum(value), color=first(color)) %>%
  ungroup %>%
  mutate(value = pmax(value, 0.)) # sweep negative prices under the rug

###save if needed
write.csv(lcop_plot, file = "./inputdata/other/lcop_avg_npi.csv", row.names = FALSE)

### continue with lcop plot

lcop_plot$component <- factor(lcop_plot$component, levels=unique(component_names$component_name))

plotted_years1 <- c(2030, 2035, 2040, 2045, 2050, 2055, 2060)

lcop_plot <- lcop_plot %>%
  filter(region %in% plotted_regions, period %in% plotted_years1) %>% 
  # mutate(route_id = route %>% as.factor() %>% as.numeric()) %>% 
  # mutate(year_id = period %>% as.factor() %>% as.numeric()) %>% 
  # mutate(n_routes = max(route_id)) %>%
  # mutate(year_label_pos = (n_routes+2) * year_id) %>% 
  # mutate(pos = year_label_pos + route_id - (n_routes+1)/2.) %>% 
  # select(-year_id, -route_id, -n_routes) %>%
  left_join(region_names, by="region") %>% 
  select(-region) %>% 
  rename(region = region_name) %>%
  mutate(region = factor(region, levels=unique(region_names$region_name))) 

# route_label <- lcop_plot %>% 
#   select(route, pos, region) %>% 
#   unique()

# year_label <- lcop_plot %>% 
#   select(period, year_label_pos, region) %>% 
#   unique()

# routes = unique(route_names$route_name)


  

# xmin <- min(lcop_plot$pos) - 1.
# xmax <- max(lcop_plot$pos) + 1.


###################################################
# VARIABLE FILTER:
### setting some inputs and regions  to zero allows to build up plots step by step in presentations

  
component_names <- component_names %>%
  filter(color %in% unique(lcop_plot$color))


comp_non_zero = c("Emission Cost", "Electricity", "Hydrogen", "Non-H2 Gases", "Liquids", "Solids", "Scrap", "Iron Ore", "DRI Pellets", "OPEX", "CAPEX")

regi_non_zero = c("EU", "China", "USA", "India")

lcop_plot <- lcop_plot %>% 
  filter(component %in% unique(component_names$component_name))


total_lcop <- lcop_plot %>%
  group_by(period, region) %>%
  summarize(value = sum(value)) %>%
  ungroup()

###################################################
# PLOT

p.lcop <- ggplot() +
  geom_bar(data=lcop_plot, position="stack", stat="identity",
           aes(x = period, y = value, fill=component)) +
  # xlim(xmin, xmax) +
  geom_text(aes(period, value+40, label = round(value,0), fill = NULL), data = total_lcop) +
  ylim(-1.,1251) +
  facet_wrap(~region) +
  scale_fill_manual(values=unique(component_names$color)) +
  # geom_text(data=year_label, aes(label = period), x = year_label$year_label_pos, y = -600., size = fs/2.5, parse = T) +
  # geom_point(data=priceSteel_plot, aes(x = pos, y = price, shape=shape)) +
  theme(text=element_text(size=fs),
        axis.text.y=element_text(size=fs),
        strip.text = element_text(size = 1.2 * fs)) +
  labs(y = "LCOP [$/t]", fill="Cost Component",
      x = "Period", title = "Average levelized cost of steel, weighted by production route (Fast transition, 820)")

# ggsave(filename = "figs_temp/lcop_avg_fastTransition820.png", width= 8, height = 6, device='png', dpi=300)

p.lcop

```
